// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The Rime Engine Authors.

//! The ground's material, **generated rather than authored** (m17.8b,
//! [ADR-0041](../../../docs/adr/0041-the-visual-bar-m17.md) Ruling 5).
//!
//! Ruling 5's complaint about the block's ground is not that it is ugly, it is that it makes the
//! renderer *unjudgeable*: "there is no normal variation for a reflection to bend around, no albedo
//! for a bounce to tint, and no detail for a shadow to read against". SSR, DDGI bounce and shadow
//! quality all get graded against the largest surface in the frame, and a constant-colour plane
//! grades every one of them a pass. So the ground needs real maps, and the ruling asks for them to
//! arrive through M16's asset path — "the first thing to use M16's asset path over a large area,
//! which is a proof M16 never got".
//!
//! There is no texture art in this repository — the whole of `assets/` is four hand-authored glTF
//! files and not one image — so the maps are **synthesised here** instead of committed as PNGs.
//! That is the same call the engine already makes for its font (it owns a 5x7 + SDF face rather
//! than depending on one) and the same shape as [`crate::fracture`]: the *config is the source*, so
//! there is no input file, and the cooked bytes stay derived data the manifest can regenerate at
//! any time.
//!
//! ## Why the noise is periodic
//!
//! The ground tiles: `ground::derive_mesh` lays down uv = world_xz / `tile_metres`, so one texture
//! repeats every few metres across a surface tens of metres wide. A texture that does not wrap
//! seamlessly therefore does not show a subtle seam — it shows a *grid* of them, dozens across the
//! frame, which reads far worse than the flat colour it replaced.
//!
//! So every octave here is **value noise on a lattice wrapped modulo its own period**, and every
//! period divides the [0,1) uv domain exactly. Wrapping the lattice is what makes the left edge and
//! the right edge interpolate against the *same* lattice values, which is what makes the seam
//! disappear — an exact, structural property rather than a blend that hides it. `seam_is_invisible`
//! in the tests below asserts it by measuring across the wrap and comparing against the texture's
//! own interior gradient.

use crate::texture::{ColorSpace, Texture};

/// The cook's default map size. Square and a power of two so the mip chain bottoms out cleanly at
/// 1x1. At the block's 4 m `tile_metres` this is 128 texels per metre of road.
pub const DEFAULT_RESOLUTION: u32 = 512;

/// The cook's default seed. Fixed, because the asset id is a hash of the generated bytes: a seed
/// that moved would re-mint the id on every cook and defeat the cook cache.
pub const DEFAULT_SEED: u32 = 0x9e37_79b9;

/// The three maps a metallic-roughness ground needs, ready to cook.
pub struct GroundMaps {
    /// Base colour, sRGB-encoded (the cook tags it `Srgb` and the GPU decodes to linear).
    pub albedo: Texture,
    /// Tangent-space normal, linear. (128,128,255) is flat.
    pub normal: Texture,
    /// glTF's packing: G = roughness, B = metallic. Linear data, never colour.
    pub metallic_roughness: Texture,
}

/// A 32-bit integer hash of a lattice point. Any decent avalanche function works; this is the
/// standard xor-shift/multiply chain. It must be a *pure function of the wrapped coordinates*,
/// which is what lets two opposite edges of the texture agree exactly.
fn hash2(x: i32, y: i32, seed: u32) -> f32 {
    let mut h = (x as u32).wrapping_mul(0x8da6_b343)
        ^ (y as u32).wrapping_mul(0xd816_3841)
        ^ seed.wrapping_mul(0xcb1a_b31f);
    h ^= h >> 15;
    h = h.wrapping_mul(0x2c1b_3c6d);
    h ^= h >> 12;
    h = h.wrapping_mul(0x297a_2d39);
    h ^= h >> 15;
    // 24 bits is ample for a texture and keeps the conversion exact in f32.
    (h & 0x00ff_ffff) as f32 / 16_777_216.0
}

/// Value noise over a lattice of `period` cells across the unit uv square, wrapped modulo `period`.
/// Smoothstep interpolation gives a continuous first derivative, which matters here because the
/// normal map is the *gradient* of this field — with linear interpolation the derivative is
/// piecewise constant and the normals would visibly facet along lattice lines.
fn value_noise(u: f32, v: f32, period: i32, seed: u32) -> f32 {
    let x = u * period as f32;
    let y = v * period as f32;
    let x0 = x.floor() as i32;
    let y0 = y.floor() as i32;
    let fx = x - x0 as f32;
    let fy = y - y0 as f32;
    let sx = fx * fx * (3.0 - 2.0 * fx);
    let sy = fy * fy * (3.0 - 2.0 * fy);

    // The wrap. `rem_euclid` rather than `%` because `%` keeps the sign in Rust and a negative
    // lattice index would hash to a different cell than its positive twin.
    let w = |a: i32| a.rem_euclid(period);
    let n00 = hash2(w(x0), w(y0), seed);
    let n10 = hash2(w(x0 + 1), w(y0), seed);
    let n01 = hash2(w(x0), w(y0 + 1), seed);
    let n11 = hash2(w(x0 + 1), w(y0 + 1), seed);

    let a = n00 + (n10 - n00) * sx;
    let b = n01 + (n11 - n01) * sx;
    a + (b - a) * sy
}

/// Fractal sum of `octaves` value-noise layers, each at twice the previous frequency and half its
/// amplitude. Doubling the period keeps every octave an exact divisor of the uv domain, so the sum
/// tiles for the same reason each term does. Normalised by the amplitude sum, so the result stays
/// in [0,1] whatever the octave count.
fn fbm(u: f32, v: f32, base_period: i32, octaves: u32, seed: u32) -> f32 {
    let mut sum = 0.0;
    let mut amp = 1.0;
    let mut norm = 0.0;
    let mut period = base_period;
    for o in 0..octaves {
        sum += amp * value_noise(u, v, period, seed.wrapping_add(o.wrapping_mul(7919)));
        norm += amp;
        amp *= 0.5;
        period *= 2;
    }
    sum / norm
}

/// The height field the other three maps are read off. Two scales on purpose: a coarse undulation
/// that survives into the distance and gives SSR something to bend around, and a fine grit that
/// only reads up close and keeps the surface from looking like poured plastic.
fn height(u: f32, v: f32, seed: u32) -> f32 {
    let swell = fbm(u, v, 4, 5, seed);
    let grit = fbm(u, v, 32, 3, seed ^ 0x5bd1_9e0f);
    0.72 * swell + 0.28 * grit
}

/// Encode a linear reflectance to an sRGB byte. The albedo texture is tagged `Srgb`, which means
/// its *bytes* carry the transfer function and the sampler undoes it — so the value written here
/// has to be encoded, not the raw linear number.
fn linear_to_srgb_byte(c: f32) -> u8 {
    let c = c.clamp(0.0, 1.0);
    let s = if c <= 0.003_130_8 {
        12.92 * c
    } else {
        1.055 * c.powf(1.0 / 2.4) - 0.055
    };
    (s * 255.0 + 0.5) as u8
}

fn unorm_byte(c: f32) -> u8 {
    (c.clamp(0.0, 1.0) * 255.0 + 0.5) as u8
}

/// The mean linear albedo and roughness are **deliberately the palette's old flat values**
/// (`opaque(0.10, 0.10, 0.11, kStreetRoughness = 0.45)`): this brick is supposed to add variation,
/// not relight the scene. `palette.cpp` explains why the road is dark and comparatively smooth —
/// "at dusk the road is what carries the lamp highlights, and a matte road at this light level is a
/// black hole with buildings floating on it" — and moving the mean would quietly invalidate that
/// tuning along with every lighting number measured against it.
const ALBEDO_MEAN: [f32; 3] = [0.10, 0.10, 0.11];
const ALBEDO_SWING: f32 = 0.035;
const ROUGHNESS_MEAN: f32 = 0.45;
const ROUGHNESS_SWING: f32 = 0.13;

/// The steepest tilt any texel's normal is allowed, in degrees — the map is normalised to hit
/// exactly this at its steepest point.
///
/// A TARGET, NOT A GAIN, and that is the fix for a real bug. The first version multiplied the
/// gradient by a constant and then divided by the resolution a second time (the gradient was
/// already a slope), so the tilt scaled as 1/resolution: the 64-texel map the tests exercise came
/// out around 16 degrees while the 512-texel map that actually ships came out around 4, and the
/// comment above it claimed the result was "independent of `resolution`". Normalising to a measured
/// maximum makes that claim true by construction instead of by assertion, and it is checked at two
/// resolutions by `tilt_is_resolution_independent`.
///
/// 12 degrees is chosen the way the old constant was — high enough that a reflection visibly bends
/// across the road, low enough that asphalt does not read as crumpled foil.
const MAX_TILT_DEGREES: f32 = 12.0;

/// Generate all three maps at `resolution` x `resolution`.
///
/// Resolution is square and a power of two so the mip chain bottoms out cleanly at 1x1; 512 is the
/// caller's default, which is 4 m of road at a comfortable texel density and costs ~350 KB as BC7
/// including mips.
pub fn generate(resolution: u32, seed: u32) -> GroundMaps {
    let n = resolution as usize;
    assert!(n >= 4, "ground textures need a lattice to interpolate over");

    // Height first, as its own buffer: the normal map is a *finite difference* of it, and computing
    // the field once means the differences are taken against exactly the values the albedo used,
    // rather than against a re-evaluation that could drift.
    let mut field = vec![0.0f32; n * n];
    for y in 0..n {
        for x in 0..n {
            let u = x as f32 / n as f32;
            let v = y as f32 / n as f32;
            field[y * n + x] = height(u, v, seed);
        }
    }

    // Toroidal fetch. The wrap here is what makes the *normal* map tile as well as the height it
    // came from — central differences at column 0 have to reach column n-1, not clamp.
    let at = |x: isize, y: isize| -> f32 {
        let xi = x.rem_euclid(n as isize) as usize;
        let yi = y.rem_euclid(n as isize) as usize;
        field[yi * n + xi]
    };

    // The gradient field, as its own pass. Two reasons it is not folded into the loop below: the
    // normalisation needs the maximum over the WHOLE field before any normal can be written, and
    // computing it once means the albedo and the normal are read off exactly the same numbers.
    //
    // Central differences scaled by the texel count: the field is defined over [0,1), so a one-texel
    // step is 1/n in uv, and dividing by it turns the difference into a slope — a quantity that
    // converges as `resolution` rises rather than scaling with it.
    let mut grad = vec![(0.0f32, 0.0f32); n * n];
    let mut steepest = 0.0f32;
    for y in 0..n {
        for x in 0..n {
            let du =
                (at(x as isize + 1, y as isize) - at(x as isize - 1, y as isize)) * 0.5 * n as f32;
            let dv =
                (at(x as isize, y as isize + 1) - at(x as isize, y as isize - 1)) * 0.5 * n as f32;
            grad[y * n + x] = (du, dv);
            steepest = steepest.max((du * du + dv * dv).sqrt());
        }
    }
    // Scale so the steepest texel lands exactly on the target tilt. `tan` because the normal's tilt
    // from vertical is `atan(|gradient| * gain)`.
    let gain = if steepest > 0.0 {
        MAX_TILT_DEGREES.to_radians().tan() / steepest
    } else {
        0.0
    };

    let mut albedo = vec![0u8; n * n * 4];
    let mut normal = vec![0u8; n * n * 4];
    let mut mr = vec![0u8; n * n * 4];

    for y in 0..n {
        for x in 0..n {
            let i = (y * n + x) * 4;
            let h = field[y * n + x];
            // Centre the field on zero so the mean lands on the constants above rather than on
            // whatever the noise's own mean happens to be.
            let d = h - 0.5;

            // ── albedo ──
            for c in 0..3 {
                albedo[i + c] = linear_to_srgb_byte(ALBEDO_MEAN[c] + ALBEDO_SWING * 2.0 * d);
            }
            albedo[i + 3] = 255;

            // ── normal, from the gradient of the height field ──
            // Negated because the normal tilts *away* from an upslope. +Y green, the glTF/OpenGL
            // convention this engine's materials already speak — and the one `compute_tangents`
            // builds a bitangent for, so the two agree about which way green points.
            let (du, dv) = grad[y * n + x];
            let mut nx = -du * gain;
            let mut ny = -dv * gain;
            let mut nz = 1.0f32;
            let len = (nx * nx + ny * ny + nz * nz).sqrt();
            nx /= len;
            ny /= len;
            nz /= len;
            normal[i] = unorm_byte(nx * 0.5 + 0.5);
            normal[i + 1] = unorm_byte(ny * 0.5 + 0.5);
            normal[i + 2] = unorm_byte(nz * 0.5 + 0.5);
            normal[i + 3] = 255;

            // ── metallic-roughness ──
            // Rougher in the hollows, smoother on the crests: worn asphalt polishes where it is
            // walked and driven on. This is the map SSR reads, so its variation is the point.
            mr[i] = 0;
            mr[i + 1] = unorm_byte(ROUGHNESS_MEAN - ROUGHNESS_SWING * 2.0 * d);
            mr[i + 2] = 0; // asphalt is a dielectric; metallic stays 0 everywhere
            mr[i + 3] = 255;
        }
    }

    GroundMaps {
        albedo: Texture::from_rgba8(resolution, resolution, ColorSpace::Srgb, albedo),
        normal: Texture::from_rgba8(resolution, resolution, ColorSpace::Linear, normal),
        metallic_roughness: Texture::from_rgba8(resolution, resolution, ColorSpace::Linear, mr),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn channel(t: &Texture, x: usize, y: usize, c: usize) -> i32 {
        let n = t.width as usize;
        t.level0[(y * n + x) * 4 + c] as i32
    }

    /// The property the whole module exists for. A tiling texture whose two edges disagree shows a
    /// grid of seams across the ground, so this measures the step ACROSS the wrap (column n-1 to
    /// column 0) and requires it to be no worse than the texture's own interior gradient.
    ///
    /// Comparing against the interior rather than against a fixed tolerance is what makes this a
    /// real proof: it fails for a non-wrapping generator at any noise amplitude, and it cannot be
    /// passed by simply making the texture flatter.
    #[test]
    fn seam_is_invisible() {
        let maps = generate(64, 12345);
        for (name, tex) in [
            ("albedo", &maps.albedo),
            ("normal", &maps.normal),
            ("metallic_roughness", &maps.metallic_roughness),
        ] {
            let n = tex.width as usize;
            let mut worst_seam = 0;
            let mut worst_interior = 0;
            for y in 0..n {
                for c in 0..3 {
                    // across the wrap
                    worst_seam =
                        worst_seam.max((channel(tex, 0, y, c) - channel(tex, n - 1, y, c)).abs());
                    // a representative interior step, same row, same channel
                    for x in 1..n {
                        worst_interior = worst_interior
                            .max((channel(tex, x, y, c) - channel(tex, x - 1, y, c)).abs());
                    }
                }
            }
            assert!(
                worst_seam <= worst_interior,
                "{name}: step across the wrap ({worst_seam}) exceeds the largest interior step \
                 ({worst_interior}) — the texture does not tile"
            );
        }
        // Vertical wrap too, for EVERY map — the lattice is wrapped in both axes and a one-axis
        // bug is easy to miss. Checking only the albedo would also have missed a wrap bug in the
        // normal map's own `at()` fetch, which is a second, independent piece of index arithmetic.
        for (name, tex) in [
            ("albedo", &maps.albedo),
            ("normal", &maps.normal),
            ("metallic_roughness", &maps.metallic_roughness),
        ] {
            let n = tex.width as usize;
            let mut worst_seam = 0;
            let mut worst_interior = 0;
            for x in 0..n {
                for c in 0..3 {
                    worst_seam =
                        worst_seam.max((channel(tex, x, 0, c) - channel(tex, x, n - 1, c)).abs());
                    for y in 1..n {
                        worst_interior = worst_interior
                            .max((channel(tex, x, y, c) - channel(tex, x, y - 1, c)).abs());
                    }
                }
            }
            assert!(
                worst_seam <= worst_interior,
                "{name}: step across the vertical wrap ({worst_seam}) exceeds the largest interior \
                 step ({worst_interior}) — the texture does not tile vertically"
            );
        }
    }

    /// The maps must vary, or this brick bought nothing: Ruling 5's whole complaint is that a
    /// constant surface makes SSR, DDGI and shadows unjudgeable. A generator that silently degraded
    /// to a flat fill would still tile perfectly, so `seam_is_invisible` alone cannot catch it.
    #[test]
    fn the_maps_actually_vary() {
        let maps = generate(64, 7);
        for (name, tex, c) in [
            ("albedo", &maps.albedo, 0usize),
            ("normal x", &maps.normal, 0),
            ("normal y", &maps.normal, 1),
            ("roughness", &maps.metallic_roughness, 1),
        ] {
            let n = tex.width as usize;
            let mut lo = 255;
            let mut hi = 0;
            for y in 0..n {
                for x in 0..n {
                    let s = channel(tex, x, y, c);
                    lo = lo.min(s);
                    hi = hi.max(s);
                }
            }
            assert!(
                hi - lo >= 8,
                "{name} spans only {lo}..{hi} — the surface is effectively flat"
            );
        }
    }

    /// Metallic stays 0 everywhere: asphalt is a dielectric, and a stray metallic term would make
    /// the largest surface in the frame reflect like a mirror under the lamps.
    #[test]
    fn the_road_is_never_metal() {
        let maps = generate(32, 3);
        let n = maps.metallic_roughness.width as usize;
        for y in 0..n {
            for x in 0..n {
                assert_eq!(channel(&maps.metallic_roughness, x, y, 2), 0);
            }
        }
    }

    /// The steepest normal must be the SAME ANGLE whatever the map resolution.
    ///
    /// This is the bug this test was written for. The gradient was multiplied by a constant and
    /// then divided by the resolution a second time — the gradient was already a slope — so the
    /// tilt scaled as 1/resolution: about 16 degrees on the 64-texel maps the other tests here
    /// exercise and about 4 on the 512-texel map that actually ships. Every other test passed,
    /// because every other test runs at one resolution.
    #[test]
    fn tilt_is_resolution_independent() {
        fn steepest_tilt_degrees(t: &Texture) -> f32 {
            let n = t.width as usize;
            let mut worst = 0.0f32;
            for i in 0..(n * n) {
                let d = |c: usize| (t.level0[i * 4 + c] as f32 / 255.0) * 2.0 - 1.0;
                let (x, y, z) = (d(0), d(1), d(2));
                worst = worst.max((x * x + y * y).sqrt().atan2(z).to_degrees());
            }
            worst
        }
        let small = steepest_tilt_degrees(&generate(64, 4242).normal);
        let large = steepest_tilt_degrees(&generate(512, 4242).normal);
        // Both hit the target; the tolerance is byte quantisation, not slack for a trend.
        for (name, got) in [("64", small), ("512", large)] {
            assert!(
                (got - MAX_TILT_DEGREES).abs() < 0.5,
                "{name}: steepest tilt {got:.2} deg, wanted {MAX_TILT_DEGREES:.2}"
            );
        }
        assert!(
            (small - large).abs() < 0.5,
            "tilt moved with resolution: {small:.2} deg at 64 vs {large:.2} at 512"
        );
    }

    /// Same seed, same bytes — the cook hashes content into an `AssetId`, so a generator that
    /// wobbled would mint a new id on every cook and defeat the cache.
    #[test]
    fn generation_is_deterministic() {
        let a = generate(32, 99);
        let b = generate(32, 99);
        assert_eq!(a.albedo.level0, b.albedo.level0);
        assert_eq!(a.normal.level0, b.normal.level0);
        assert_eq!(a.metallic_roughness.level0, b.metallic_roughness.level0);
    }
}
