// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The Rime Engine Authors.
//
// 01-hello-triangle — the M3.3 proof, runnable form. It brings up the RHI, renders Rime's first
// triangle into an off-screen image, reads the pixels back, and prints an ASCII preview so a human
// can see the result with no window and no GPU image viewer. This is the "first pixels" milestone:
// the same render is asserted pixel-by-pixel by tests/rhi/offscreen_triangle_test (the CI gate).
//
// M3.4 will upgrade this same sample to present the triangle in a real window via a swapchain (and
// finally map the M2 Wayland surface); for now, off-screen keeps it runnable anywhere — including
// on the software GPU (lavapipe) used in CI.
//
// Run it:   build/dev/bin/hello_triangle

#include <cstdint>
#include <cstdio>
#include <vector>

#include "rime/rhi/rhi.hpp"
#include "triangle_render.hpp"

// Generated by rime_add_shaders from shaders/triangle.{vert,frag} (ADR-0008, offline compile).
#include "triangle.frag.spv.h"
#include "triangle.vert.spv.h"

int main() {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "01-hello-triangle";

    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr,
                     "01-hello-triangle: no Vulkan device available — is a driver or a software "
                     "ICD (e.g. lavapipe / MoltenVK) installed?\n");
        return 1;
    }
    std::printf("01-hello-triangle: rendering on '%s'\n", device->adapter().name.c_str());

    const std::uint32_t size = 32; // small, so the ASCII preview fits a terminal
    const rime::rhi::ClearColor clear{0.1f, 0.1f, 0.3f, 1.0f};
    const std::vector<std::uint8_t> pixels =
        rime_sample::render_triangle_offscreen(*device,
                                               size,
                                               clear,
                                               triangle_vert_spv,
                                               sizeof(triangle_vert_spv),
                                               triangle_frag_spv,
                                               sizeof(triangle_frag_spv));

    // Map each pixel's brightness (weighted toward red, since the triangle is red) onto a character
    // ramp: the red triangle shows up brighter than the dark-blue cleared background.
    static const char ramp[] = " .:-=+*#%@";
    for (std::uint32_t y = 0; y < size; ++y) {
        for (std::uint32_t x = 0; x < size; ++x) {
            const std::uint8_t* p = &pixels[(static_cast<std::size_t>(y) * size + x) * 4];
            const int luminance = (p[0] * 3 + p[1] + p[2]) / 5; // 0..~255
            const int idx = luminance * 9 / 255;                // 0..9 into the ramp
            std::putchar(ramp[idx]);
        }
        std::putchar('\n');
    }

    std::printf("01-hello-triangle: rendered a %ux%u triangle off-screen. First pixels!\n",
                size,
                size);
    return 0;
}
