#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 The Rime Engine Authors.
"""Sources for the m19.8e end-to-end splat world (ADR-0073). Run by regen.sh, never by a test.

Writes only SOURCES — PNGs, raw .r16 heights and TOML sidecars. Every cooked byte in this directory
is produced by the `rime` CLI from them (regen.sh), which is the point of the fixture: the C++ test
draws what the real cook wrote, not a C++ imitation of it.

  layers <material-id-hex>        two terrain-layer sources (grass, rock) over the cooked material
  tiles  <grass-id> <rock-id>     a 4x4 world of 9x9-sample tiles, each with a 5x5 splat map
"""
import math
import struct
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
SRC = HERE / "src"
N = 9            # samples per tile side
TILES = 4        # level-0 tiles per axis
SIZE = 8.0       # metres per tile (1 m cells)
SPLAT = 5        # splat texels per tile side


def height_q(gx, gz):
    """One GLOBAL field, so every shared border agrees: hills plus a ridge, in 1 mm steps."""
    x, z = gx / 32.0, gz / 32.0
    h = 4.0 + 3.0 * math.sin(5.1 * x + 0.7) * math.cos(3.7 * z) + 2.5 * math.exp(-((x - 0.6) ** 2 + (z - 0.3) ** 2) * 18.0)
    h += 0.35 * math.sin(1.9 * gx + 0.5 * gz)  # sample-scale roughness: parents really differ
    return max(0, min(65535, round(h * 1000.0)))


def rock_weight(u, v):
    """0..255 rock share at world position (u, v) in tiles: rock on the ridge, grass elsewhere."""
    r = math.exp(-((u / TILES - 0.6) ** 2 + (v / TILES - 0.3) ** 2) * 10.0) + 0.25 * math.sin(3.0 * u) * math.cos(2.0 * v)
    return max(0, min(255, round(255 * r)))


def layers(material_id):
    SRC.mkdir(exist_ok=True)
    for name, base, contrast, scale in (("grass", (70, 120, 40), 4.0, 2.0), ("rock", (120, 112, 104), 8.0, 3.0)):
        albedo = Image.new("RGB", (8, 8))
        height = Image.new("I;16", (8, 8))
        for y in range(8):
            for x in range(8):
                k = (x * 37 + y * 23) % 17 - 8
                albedo.putpixel((x, y), tuple(max(0, min(255, c + 3 * k)) for c in base))
                height.putpixel((x, y), (x * 8191 + y * 4099 + (x * y * 977)) % 65536)
        albedo.save(SRC / f"{name}_albedo.png")
        height.save(SRC / f"{name}_height.png")
        (SRC / f"{name}.terrainlayer.toml").write_text(
            f"# m19.8e splat world: the {name} layer (generated by gen_splat_world.py)\n"
            f"material = 0x{material_id}\n"
            f'albedo = "{name}_albedo.png"\n'
            f'height = "{name}_height.png"\n'
            f"uv_scale = [{scale}, {scale}]\n"
            f"height_contrast = {contrast}\n")


def tiles(grass_id, rock_id):
    SRC.mkdir(exist_ok=True)
    desc = ["# m19.8e end-to-end splat world (ADR-0073): 4x4 level-0 tiles, 3 levels, baked parents.",
            "# Generated by gen_splat_world.py; cooked by regen.sh with `rime terrain-world`.",
            "levels = 3", 'palette_dir = "../palette"']
    for tz in range(TILES):
        for tx in range(TILES):
            stem = f"t_{tx}_{tz}"
            raw = b"".join(struct.pack("<H", height_q(tx * (N - 1) + i, tz * (N - 1) + j))
                           for j in range(N) for i in range(N))
            (SRC / f"{stem}.r16").write_bytes(raw)
            (SRC / f"{stem}.toml").write_text(
                f"size_x = {SIZE}\nsize_z = {SIZE}\nheight_min = 0.0\nheight_max = 65.535\n"
                f"origin_x = {tx * SIZE}\norigin_y = 0.0\norigin_z = {tz * SIZE}\n"
                f"columns = {N}\nrows = {N}\nlayer0 = 0x{grass_id}\nlayer1 = 0x{rock_id}\n")
            splat = Image.new("RGBA", (SPLAT, SPLAT))
            for j in range(SPLAT):
                for i in range(SPLAT):
                    r = rock_weight(tx + i / (SPLAT - 1), tz + j / (SPLAT - 1))
                    splat.putpixel((i, j), (255 - r, r, 0, 0))
            splat.save(SRC / f"{stem}.splat.png")
            desc.append(f'tile_{tx}_{tz} = "{stem}.r16"')
    (SRC / "splat_world.terrainworld.toml").write_text("\n".join(desc) + "\n")


if __name__ == "__main__":
    if sys.argv[1:2] == ["layers"]:
        layers(sys.argv[2])
    elif sys.argv[1:2] == ["tiles"]:
        tiles(sys.argv[2], sys.argv[3])
    else:
        sys.exit(__doc__)
