// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The Rime Engine Authors.
//
// 02-textured-quad — M3's headline "done when": a textured quad rendered through the RHI. It draws an
// indexed quad sampling a 2×2 red/green/blue/yellow texture, exercising everything M3.5 adds (index
// buffer, texture upload, sampler, descriptors). Two modes, like 01-hello-triangle:
//   * windowed (default): present the quad via a swapchain (M3.4) in a real window;
//   * off-screen (--offscreen, and the fallback where there's no display): render to an image, read
//     it back, and print a colored-letter preview — runnable anywhere, GPU-free in CI (lavapipe).
// The off-screen render is what tests/rhi/textured_quad_test asserts on, pixel by pixel.
//
// Run it:   build/dev/bin/textured_quad
//           build/dev/bin/textured_quad --frames 120
//           build/dev/bin/textured_quad --offscreen

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string_view>
#include <vector>

#include "rime/platform/platform.hpp"
#include "rime/rhi/rhi.hpp"
#include "quad_render.hpp"

// Generated by rime_add_shaders from shaders/quad.{vert,frag} (ADR-0008, offline compile).
#include "quad.frag.spv.h"
#include "quad.vert.spv.h"

namespace {

constexpr rime::rhi::ClearColor kClear{0.1f, 0.1f, 0.3f, 1.0f}; // dark blue, shows at the corners

// Reduce an RGBA pixel to a single character so the off-screen result is legible in a terminal: a
// letter for each of the texture's four colors, '.' for the dark clear background.
char color_glyph(const std::uint8_t* p) {
    const bool r = p[0] > 150, g = p[1] > 150, b = p[2] > 150;
    if (r && g) return 'Y'; // yellow
    if (r) return 'R';
    if (g) return 'G';
    if (b) return 'B';
    return '.'; // clear
}

// Off-screen path (M3.3/M3.5): render to an image, read it back, preview it. No window/display/GPU
// needed — the same render the pixel-readback CI gate asserts on.
int run_offscreen() {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "02-textured-quad";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr,
                     "02-textured-quad: no Vulkan device available — is a driver or a software "
                     "ICD (e.g. lavapipe / MoltenVK) installed?\n");
        return 1;
    }
    std::printf("02-textured-quad: rendering off-screen on '%s'\n", device->adapter().name.c_str());

    const std::uint32_t size = 32;
    const std::vector<std::uint8_t> pixels = rime_sample::render_quad_offscreen(*device,
                                                                                size,
                                                                                kClear,
                                                                                quad_vert_spv,
                                                                                sizeof(quad_vert_spv),
                                                                                quad_frag_spv,
                                                                                sizeof(quad_frag_spv));

    for (std::uint32_t y = 0; y < size; ++y) {
        for (std::uint32_t x = 0; x < size; ++x) {
            std::putchar(color_glyph(&pixels[(static_cast<std::size_t>(y) * size + x) * 4]));
        }
        std::putchar('\n');
    }
    std::printf("02-textured-quad: rendered a %ux%u textured quad off-screen "
                "(R/G/B/Y quadrants). M3 done!\n",
                size,
                size);
    return 0;
}

// Windowed path (M3.4 swapchain): present the textured quad each frame until the window closes (or
// `max_frames` is reached). Returns false when there is no window/device/surface, so main() can fall
// back to the off-screen path.
bool run_windowed(int max_frames) {
    using namespace rime::platform;

    if (!init()) {
        std::fprintf(stderr, "02-textured-quad: platform::init() failed\n");
        return false;
    }

    WindowDesc wd{};
    wd.title = "Rime — 02 textured quad";
    wd.width = 640;
    wd.height = 480;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "02-textured-quad";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }

    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        std::fprintf(stderr, "02-textured-quad: could not create a swapchain for this window\n");
        device.reset();
        shutdown();
        return false;
    }

    std::printf("02-textured-quad: presenting on '%s' (%ux%u). Press ESC or close the window.\n",
                device->adapter().name.c_str(),
                swapchain->extent().width,
                swapchain->extent().height);

    auto quad = rime_sample::make_quad(*device,
                                       swapchain->format(),
                                       quad_vert_spv,
                                       sizeof(quad_vert_spv),
                                       quad_frag_spv,
                                       sizeof(quad_frag_spv));

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames) break;

        input.new_frame();
        Event e{};
        while (poll_event(e)) input.process(e);
        if (input.key_pressed(Key::Escape)) window->request_close();

        rime::rhi::TextureHandle target = swapchain->acquire_next_image();
        if (!target.is_valid()) {
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            continue;
        }

        auto cmd = device->begin_commands();
        rime_sample::record_quad(*cmd, quad, target, swapchain->extent(), kClear);
        if (!swapchain->present(*cmd)) {
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
        }
        ++frames;
    }

    device->wait_idle();
    rime_sample::destroy_quad(*device, quad);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("02-textured-quad: presented %d frame%s. A textured quad, on screen!\n",
                frames,
                frames == 1 ? "" : "s");
    return true;
}

} // namespace

int main(int argc, char** argv) {
    bool offscreen = false;
    int frames = 0;
    for (int i = 1; i < argc; ++i) {
        const std::string_view a(argv[i]);
        if (a == "--offscreen" || a == "--headless") {
            offscreen = true;
        } else if (a == "--windowed") {
            offscreen = false;
        } else if (a == "--frames" && i + 1 < argc) {
            frames = std::atoi(argv[++i]);
        }
    }

    if (offscreen) return run_offscreen();
    if (run_windowed(frames)) return 0;
    std::printf("02-textured-quad: no window/display available — falling back to off-screen.\n");
    return run_offscreen();
}
