// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The Rime Engine Authors.
//
// 03-icem-viewer — the ICEM viewer. It loads a computed part (a binary STL, e.g. ICEM's brick6
// thrust chamber) and draws it depth-correct and lit, orbitable with the mouse; cuts a
// cross-section to see inside it (B2); and, when a computed simulation field is supplied (ICEM's
// .icef, e.g. the brick23 temperature field), colours the part — and the interior the cut reveals —
// by that field with a colormap + legend (C1). Two modes, like the other samples:
//   * windowed (default): present via the swapchain — drag to orbit, right-drag to pan, wheel to
//   zoom,
//     F to reframe, C to toggle the section, G to toggle the field colormap, ESC to quit;
//   * off-screen (--offscreen [file.ppm]): render one frame to a file (and print coverage) —
//   runnable
//     anywhere, GPU-free in CI. tests/rhi/mesh_offscreen_test asserts on this exact render.
//
// Run it:   icem_viewer field.stl --field field.icef    # part coloured by the field
//           icem_viewer field.stl                        # auto-loads the sibling field.icef
//           icem_viewer part.stl --offscreen v.ppm --clip z --field field.icef
//           icem_viewer viscous.stl --flow velocity      # streamlines of the computed flow (D)
//           icem_viewer viscous.stl --dvr --speed        # DVR of the speed boundary layer (D2)
//           icem_viewer --assembly tokamak/              # many parts: colour, toggle, explode (E1)
//           icem_viewer                                  # no file -> a unit cube, runs anywhere

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "assembly.hpp"
#include "camera.hpp"
#include "cap.hpp"
#include "field.hpp"
#include "iso.hpp"
#include "legend.hpp"
#include "mesh_render.hpp"
#include "provenance.hpp"
#include "provenance_view.hpp"
#include "rime/platform/platform.hpp"
#include "rime/rhi/rhi.hpp"
#include "stl.hpp"
#include "streamlines.hpp"
#include "turntable.hpp"
#include "ui.hpp"
#include "ui_render.hpp"
#include "warp.hpp"

// Generated by rime_add_shaders from shaders/*.{vert,frag} (ADR-0008, offline compile).
#include "cap.frag.spv.h"
#include "cap.vert.spv.h"
#include "capmark.frag.spv.h"
#include "iso.frag.spv.h"
#include "iso.vert.spv.h"
#include "legend.frag.spv.h"
#include "legend.vert.spv.h"
#include "mesh.frag.spv.h"
#include "mesh.vert.spv.h"
#include "streamline.frag.spv.h"
#include "streamline.vert.spv.h"
#include "ui.frag.spv.h"
#include "ui.vert.spv.h"
#include "warp.frag.spv.h"
#include "warp.vert.spv.h"

namespace {

using rime::viewer::CpuMesh;
using rime::viewer::MeshPush;
using rime::viewer::OrbitCamera;
using rime::viewer::ScalarField;
using rime::viewer::VectorField;

constexpr rime::rhi::ClearColor kClear{0.08f, 0.09f, 0.11f, 1.0f}; // dark studio background

// Point the camera at the part: frame its bounding sphere, set near/far to bracket it, and start
// from a pleasant three-quarter view. ICEM authors parts z-up (cylinders/revolves about z), so that
// is the default orbit axis.
void setup_camera(OrbitCamera& cam, const CpuMesh& mesh, float aspect, rime::core::Vec3 world_up) {
    const float r = std::max(mesh.radius(), 1e-4f);
    cam.world_up = world_up;
    cam.z_near = std::max(r * 0.02f, 1e-4f);
    cam.z_far = r * 100.0f + 10.0f;
    cam.min_distance = r * 0.05f;
    cam.max_distance = r * 100.0f;
    cam.frame(mesh.center(), r, aspect);
    cam.yaw = rime::core::radians(35.0f);
    cam.pitch = rime::core::radians(20.0f);
}

// Interactive cross-section state: a world-axis-aligned plane that cuts the part open. `axis` picks
// the plane normal (x/y/z), `sign` which half is removed, `offset` where along the axis the plane
// sits.
struct Clip {
    bool on = false;
    int axis = 0;        // 0 = x, 1 = y, 2 = z
    float sign = 1.0f;   // +1 removes the +axis half, -1 the −axis half
    float offset = 0.0f; // plane position along the axis, in world units
};

rime::core::Vec3 axis_unit(int axis) {
    return axis == 0   ? rime::core::Vec3{1, 0, 0}
           : axis == 1 ? rime::core::Vec3{0, 1, 0}
                       : rime::core::Vec3{0, 0, 1};
}

// Fill a (scale, bias) push pair from a loaded field, or zero it (which the shader reads as "no
// field": the neutral metal albedo). vmin/vmax ride in the .w components; the field is "on" iff
// vmax > vmin.
void fill_field(float scale[4], float bias[4], const ScalarField* field, bool on) {
    if (field && on) {
        for (int c = 0; c < 3; ++c) {
            scale[c] = field->scale[c];
            bias[c] = field->bias[c];
        }
        scale[3] = field->vmin;
        bias[3] = field->vmax;
    } else {
        scale[0] = scale[1] = scale[2] = scale[3] = 0.0f;
        bias[0] = bias[1] = bias[2] = bias[3] = 0.0f;
    }
}

void set_field_push(MeshPush& p, const ScalarField* field, bool on) {
    fill_field(p.field_scale, p.field_bias, field, on);
}

MeshPush make_push(const OrbitCamera& cam,
                   float aspect,
                   const Clip& clip,
                   const ScalarField* field,
                   bool field_on) {
    MeshPush p{};
    p.mvp = cam.view_proj(aspect);
    const rime::core::Vec3 e = cam.eye();
    p.cam_pos[0] = e.x;
    p.cam_pos[1] = e.y;
    p.cam_pos[2] = e.z;
    p.cam_pos[3] = 1.0f;
    if (clip.on) {
        // normal = sign·axis, offset w = sign·offset → discard where dot(N,p) > w cuts the chosen
        // half at coordinate `offset` (see the derivation in mesh_render.hpp / the shader).
        const rime::core::Vec3 n = axis_unit(clip.axis) * clip.sign;
        p.clip_plane[0] = n.x;
        p.clip_plane[1] = n.y;
        p.clip_plane[2] = n.z;
        p.clip_plane[3] = clip.sign * clip.offset;
    } else {
        p.clip_plane[0] = p.clip_plane[1] = p.clip_plane[2] = 0.0f;
        p.clip_plane[3] = 1e30f; // disabled: nothing is clipped
    }
    set_field_push(p, field, field_on);
    return p;
}

// Build the cap-quad push: the camera matrix, the same field colormap params as the surface, and
// the cut rectangle — a square of side ~2·radius on the cutting plane, centred on the part (the
// stencil trims it to the solid). axis/offset come from the clip.
rime::viewer::CapPush make_cap_push(const OrbitCamera& cam,
                                    float aspect,
                                    const Clip& clip,
                                    const ScalarField* field,
                                    bool field_on,
                                    const CpuMesh& mesh) {
    rime::viewer::CapPush c{};
    c.mvp = cam.view_proj(aspect);
    fill_field(c.field_scale, c.field_bias, field, field_on);

    const rime::core::Vec3 ctr = mesh.center();
    const float r = std::max(mesh.radius(), 1e-4f) * 1.05f;
    const auto comp = [](const rime::core::Vec3& p, int i) {
        return i == 0 ? p.x : i == 1 ? p.y : p.z;
    };
    const int a = clip.axis;
    const int u = (a == 0) ? 1 : 0; // the two in-plane axes (those that aren't the plane normal)
    const int v = (a == 2) ? 1 : 2;
    c.cap_rect[0] = comp(ctr, u) - r;
    c.cap_rect[1] = comp(ctr, u) + r;
    c.cap_rect[2] = comp(ctr, v) - r;
    c.cap_rect[3] = comp(ctr, v) + r;
    c.cap_meta[0] = clip.offset;
    c.cap_meta[1] = static_cast<float>(a);
    return c;
}

bool write_ppm(const std::string& path,
               const std::vector<std::uint8_t>& rgba,
               std::uint32_t w,
               std::uint32_t h) {
    std::ofstream out(path, std::ios::binary);
    if (!out)
        return false;
    out << "P6\n" << w << ' ' << h << "\n255\n";
    for (std::size_t i = 0; i < static_cast<std::size_t>(w) * h; ++i) {
        out.write(reinterpret_cast<const char*>(&rgba[i * 4]), 3); // RGB, drop alpha
    }
    return static_cast<bool>(out);
}

// Render one lit, square (aspect-1) frame of the part at camera `cam` to an RGBA8 pixel buffer. The one
// place that dispatches plain vs. sectioned (capped) rendering, shared by the single snapshot, the
// turntable export and the windowed screenshot — so all three stay pixel-for-pixel the same view. A
// sectioned frame carries the solid cap (and the field on the cut face); an unclipped one is the plain
// lit part. `cap_on` is ignored unless `clip.on`.
std::vector<std::uint8_t> render_view(rime::rhi::Device& device,
                                      const CpuMesh& mesh,
                                      const OrbitCamera& cam,
                                      std::uint32_t size,
                                      const Clip& clip,
                                      const ScalarField* field,
                                      bool field_on,
                                      bool cap_on) {
    const bool use_field = field != nullptr && field_on;
    const float* frgba = use_field ? field->rgba.data() : nullptr;
    const std::uint32_t fnx = use_field ? field->nx : 1;
    const std::uint32_t fny = use_field ? field->ny : 1;
    const std::uint32_t fnz = use_field ? field->nz : 1;
    if (clip.on) {
        return rime::viewer::render_section_offscreen(
            device, size, mesh, make_push(cam, 1.0f, clip, field, field_on),
            make_cap_push(cam, 1.0f, clip, field, field_on, mesh), kClear, cap_on, mesh_vert_spv,
            sizeof(mesh_vert_spv), mesh_frag_spv, sizeof(mesh_frag_spv), capmark_frag_spv,
            sizeof(capmark_frag_spv), cap_vert_spv, sizeof(cap_vert_spv), cap_frag_spv,
            sizeof(cap_frag_spv), frgba, fnx, fny, fnz);
    }
    return rime::viewer::render_mesh_offscreen(
        device, size, mesh, make_push(cam, 1.0f, clip, field, field_on), kClear, mesh_vert_spv,
        sizeof(mesh_vert_spv), mesh_frag_spv, sizeof(mesh_frag_spv), frgba, fnx, fny, fnz);
}

// Off-screen path: render one frame to `out_path` (PPM) and report how much of the frame the part
// covers. No window/display needed — the render the CI gate asserts on.
int run_offscreen(const CpuMesh& mesh,
                  const std::string& out_path,
                  std::uint32_t size,
                  rime::core::Vec3 world_up,
                  Clip clip,
                  const ScalarField* field,
                  bool field_on,
                  bool cap_on) {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr,
                     "icem_viewer: no Vulkan device available (driver / lavapipe / MoltenVK?)\n");
        return 1;
    }

    OrbitCamera cam;
    setup_camera(cam, mesh, 1.0f, world_up); // square image → aspect 1

    // A sectioned snapshot cuts through the part center along the chosen axis.
    if (clip.on)
        clip.offset = rime::core::dot(mesh.center(), axis_unit(clip.axis));

    const bool use_field = field != nullptr && field_on;
    const std::vector<std::uint8_t> px =
        render_view(*device, mesh, cam, size, clip, field, field_on, cap_on);

    std::size_t lit = 0;
    for (std::size_t i = 0; i < static_cast<std::size_t>(size) * size; ++i) {
        // A pixel is "part" if it is brighter than the dark background in any channel.
        if (px[i * 4 + 0] > 40 || px[i * 4 + 1] > 40 || px[i * 4 + 2] > 40)
            ++lit;
    }
    const double pct = 100.0 * static_cast<double>(lit) / (static_cast<double>(size) * size);
    std::printf(
        "icem_viewer: rendered %u triangles on '%s'%s — part covers %.1f%% of a %ux%u frame\n",
        mesh.triangle_count(),
        device->adapter().name.c_str(),
        use_field ? " (field colormap)" : "",
        pct,
        size,
        size);

    if (!write_ppm(out_path, px, size, size)) {
        std::fprintf(stderr, "icem_viewer: could not write '%s'\n", out_path.c_str());
        return 1;
    }
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Turntable export (E4): render `frames` lit snapshots orbiting the part through a full 360°, one PPM
// each (numbered off the out template — icem_view.ppm → icem_view_000.ppm …), and report the render
// throughput. Headless by nature — a showcase loop over the proven off-screen path, reusing one device.
// The "perf" half: each frame is timed, and the min / avg / max ms and the frames-per-second print at the
// end, an honest measure of the engine's offscreen render+readback rate on this GPU.
int run_turntable_offscreen(const CpuMesh& mesh,
                            const std::string& out_path,
                            std::uint32_t size,
                            rime::core::Vec3 world_up,
                            Clip clip,
                            const ScalarField* field,
                            bool field_on,
                            bool cap_on,
                            int frames) {
    frames = std::max(frames, 1);
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available\n");
        return 1;
    }

    OrbitCamera cam;
    setup_camera(cam, mesh, 1.0f, world_up);
    if (clip.on)
        clip.offset = rime::core::dot(mesh.center(), axis_unit(clip.axis));
    const float yaw0 = cam.yaw;

    std::printf("icem_viewer: turntable — %d frames of %u triangles at %ux%u on '%s'%s%s …\n",
                frames,
                mesh.triangle_count(),
                size,
                size,
                device->adapter().name.c_str(),
                (field && field_on) ? " (field colormap)" : "",
                clip.on ? " (sectioned)" : "");

    double t_sum = 0.0, t_min = 1e30, t_max = 0.0;
    for (int i = 0; i < frames; ++i) {
        cam.yaw = rime::viewer::turntable_yaw(i, frames, yaw0);
        const auto t0 = std::chrono::steady_clock::now();
        const std::vector<std::uint8_t> px =
            render_view(*device, mesh, cam, size, clip, field, field_on, cap_on);
        const double ms =
            std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
        t_sum += ms;
        t_min = std::min(t_min, ms);
        t_max = std::max(t_max, ms);

        const std::string frame_path = rime::viewer::turntable_frame_path(out_path, i);
        if (!write_ppm(frame_path, px, size, size)) {
            std::fprintf(stderr, "icem_viewer: could not write '%s'\n", frame_path.c_str());
            return 1;
        }
    }

    const double avg = t_sum / frames;
    std::printf("icem_viewer: wrote %s … %s — %.1f ms/frame avg (%.1f .. %.1f), %.1f fps\n",
                rime::viewer::turntable_frame_path(out_path, 0).c_str(),
                rime::viewer::turntable_frame_path(out_path, frames - 1).c_str(),
                avg,
                t_min,
                t_max,
                avg > 0.0 ? 1000.0 / avg : 0.0);
    return 0;
}

// Create a depth-stencil target sized to the swapchain; recreated alongside the swapchain on
// resize. D32FloatS8 (depth + stencil) so the cross-section cap's stencil pass has somewhere to
// write (ADR-0014).
rime::rhi::TextureHandle make_depth(rime::rhi::Device& device, rime::rhi::Extent2D extent) {
    rime::rhi::TextureDesc td{};
    td.extent = extent;
    td.format = rime::rhi::Format::D32FloatS8;
    td.usage = rime::rhi::TextureUsage::DepthStencil;
    td.debug_name = "icem-viewer-depthstencil";
    return device.create_texture(td);
}

// Windowed path: present the lit, orbitable part until the window closes (or max_frames is
// reached).
bool run_windowed(const CpuMesh& mesh,
                  rime::core::Vec3 world_up,
                  int max_frames,
                  const ScalarField* field,
                  bool field_on,
                  bool cap_on) {
    using namespace rime::platform;

    if (!init())
        return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer";
    wd.width = 1280;
    wd.height = 720;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }

    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }

    // Upload the field volume once (if any); toggling G only flips the cheap push-constant flag.
    const float* frgba = field ? field->rgba.data() : nullptr;
    const std::uint32_t fnx = field ? field->nx : 1;
    const std::uint32_t fny = field ? field->ny : 1;
    const std::uint32_t fnz = field ? field->nz : 1;
    auto gpu = rime::viewer::make_mesh(*device,
                                       swapchain->format(),
                                       rime::rhi::Format::D32FloatS8,
                                       mesh,
                                       mesh_vert_spv,
                                       sizeof(mesh_vert_spv),
                                       mesh_frag_spv,
                                       sizeof(mesh_frag_spv),
                                       frgba,
                                       fnx,
                                       fny,
                                       fnz);
    rime::viewer::Cap cap = rime::viewer::make_cap(*device,
                                                   swapchain->format(),
                                                   rime::rhi::Format::D32FloatS8,
                                                   mesh_vert_spv,
                                                   sizeof(mesh_vert_spv),
                                                   capmark_frag_spv,
                                                   sizeof(capmark_frag_spv),
                                                   cap_vert_spv,
                                                   sizeof(cap_vert_spv),
                                                   cap_frag_spv,
                                                   sizeof(cap_frag_spv));
    rime::viewer::Legend legend = rime::viewer::make_legend(*device,
                                                            swapchain->format(),
                                                            legend_vert_spv,
                                                            sizeof(legend_vert_spv),
                                                            legend_frag_spv,
                                                            sizeof(legend_frag_spv));
    rime::rhi::TextureHandle depth = make_depth(*device, swapchain->extent());

    OrbitCamera cam;
    {
        const rime::rhi::Extent2D e = swapchain->extent();
        setup_camera(
            cam, mesh, static_cast<float>(e.width) / static_cast<float>(e.height), world_up);
    }

    Clip clip;
    clip.offset = rime::core::dot(mesh.center(), axis_unit(clip.axis));
    const float clip_step = std::max(std::max(mesh.radius(), 1e-4f) * 0.02f, 1e-5f);
    bool show_field = field != nullptr && field_on;
    bool show_cap =
        cap_on; // a section fills its cut face by default; K toggles the solid cap (B2b)
    int shots = 0; // P-key screenshots taken this session (numbers the output files)

    std::printf(
        "icem_viewer: presenting %u triangles on '%s'.\n"
        "  camera: drag=orbit, right-drag=pan, wheel=zoom, F=reframe, ESC=quit\n"
        "  section: C=toggle, X/Y/Z=axis, N=flip side, [ ]=move plane, K=toggle solid cap\n"
        "  P=screenshot (icem_shot_NNN.ppm)\n",
        mesh.triangle_count(),
        device->adapter().name.c_str());
    if (field) {
        std::printf("  field: '%s' [%s] range %.4g .. %.4g — G=toggle colormap (%s)\n",
                    field->name.c_str(),
                    field->unit.c_str(),
                    static_cast<double>(field->vmin),
                    static_cast<double>(field->vmax),
                    show_field ? "on" : "off");
    }

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames)
            break;

        input.new_frame();
        Event e{};
        while (poll_event(e))
            input.process(e);
        if (input.key_pressed(Key::Escape))
            window->request_close();

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float h = static_cast<float>(ext.height);
        const float aspect = static_cast<float>(ext.width) / h;
        if (input.mouse_down(MouseButton::Left)) {
            cam.orbit(input.mouse_dx() * 0.008f, -input.mouse_dy() * 0.008f);
        }
        if (input.mouse_down(MouseButton::Right) || input.mouse_down(MouseButton::Middle)) {
            cam.pan(input.mouse_dx() / h, input.mouse_dy() / h);
        }
        if (input.wheel_y() != 0.0f)
            cam.zoom(input.wheel_y());
        if (input.key_pressed(Key::F))
            cam.frame(mesh.center(), std::max(mesh.radius(), 1e-4f), aspect);

        // Cross-section controls. Selecting an axis re-centers the plane on the part.
        if (input.key_pressed(Key::C))
            clip.on = !clip.on;
        if (input.key_pressed(Key::X)) {
            clip.axis = 0;
            clip.offset = rime::core::dot(mesh.center(), axis_unit(0));
        }
        if (input.key_pressed(Key::Y)) {
            clip.axis = 1;
            clip.offset = rime::core::dot(mesh.center(), axis_unit(1));
        }
        if (input.key_pressed(Key::Z)) {
            clip.axis = 2;
            clip.offset = rime::core::dot(mesh.center(), axis_unit(2));
        }
        if (input.key_pressed(Key::N))
            clip.sign = -clip.sign;
        if (input.key_down(Key::LeftBracket))
            clip.offset -= clip_step;
        if (input.key_down(Key::RightBracket))
            clip.offset += clip_step;
        // Field colormap toggle (only meaningful when a field was loaded).
        if (input.key_pressed(Key::G) && field)
            show_field = !show_field;
        // Solid-cap toggle for the cross-section (B2b).
        if (input.key_pressed(Key::K))
            show_cap = !show_cap;
        // P: screenshot the live view. Re-render it square at a crisp resolution off-screen (the same
        // render_view the snapshot/turntable use) and write a numbered PPM — no swapchain readback path
        // needed, and the saved frame is higher-res than the window.
        if (input.key_pressed(Key::P)) {
            constexpr std::uint32_t shot_size = 1024;
            const std::vector<std::uint8_t> shot =
                render_view(*device, mesh, cam, shot_size, clip, field, show_field, show_cap);
            const std::string name = rime::viewer::turntable_frame_path("icem_shot.ppm", shots);
            if (write_ppm(name, shot, shot_size, shot_size)) {
                std::printf("icem_viewer: screenshot → %s (%ux%u)\n", name.c_str(), shot_size,
                            shot_size);
                ++shots;
            } else {
                std::fprintf(stderr, "icem_viewer: could not write screenshot '%s'\n", name.c_str());
            }
        }

        rime::rhi::TextureHandle target = swapchain->acquire_next_image();
        if (!target.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
            continue;
        }

        auto cmd = device->begin_commands();
        rime::viewer::record_section(*cmd,
                                     gpu,
                                     cap,
                                     target,
                                     depth,
                                     ext,
                                     make_push(cam, aspect, clip, field, show_field),
                                     make_cap_push(cam, aspect, clip, field, show_field, mesh),
                                     kClear,
                                     clip.on && show_cap);
        if (field && show_field)
            rime::viewer::record_legend(*cmd, legend, target, ext);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
        }
        ++frames;
    }

    device->wait_idle();
    device->destroy(depth);
    rime::viewer::destroy_legend(*device, legend);
    rime::viewer::destroy_cap(*device, cap);
    rime::viewer::destroy_mesh(*device, gpu);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

// Replace a path's extension (or append, if it has none): so `chamber.stl` pairs with its sibling
// `chamber.icef` / `chamber.icejson`. Returns empty for an empty path.
std::string replace_extension(const std::string& path, const char* ext) {
    if (path.empty())
        return {};
    const std::size_t slash = path.find_last_of("/\\");
    const std::size_t dot = path.find_last_of('.');
    if (dot != std::string::npos && (slash == std::string::npos || dot > slash))
        return path.substr(0, dot) + ext;
    return path + ext;
}

// The sibling computed-field file for an STL path (ICEM's `field.stl` pairs with its `field.icef`).
std::string sibling_icef(const std::string& stl_path) { return replace_extension(stl_path, ".icef"); }

// Off-screen warped snapshot: a static peak-deformation view (gain = 25% of the part radius).
int run_warp_offscreen(const CpuMesh& mesh,
                       const std::string& out_path,
                       std::uint32_t size,
                       rime::core::Vec3 world_up,
                       const VectorField& vf) {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available\n");
        return 1;
    }
    OrbitCamera cam;
    setup_camera(cam, mesh, 1.0f, world_up);
    const float r = std::max(mesh.radius(), 1e-4f);

    MeshPush p{};
    p.mvp = cam.view_proj(1.0f);
    const rime::core::Vec3 e = cam.eye();
    p.cam_pos[0] = e.x;
    p.cam_pos[1] = e.y;
    p.cam_pos[2] = e.z;
    p.cam_pos[3] = 1.0f;
    p.clip_plane[0] = p.clip_plane[1] = p.clip_plane[2] = 0.0f;
    p.clip_plane[3] = 1e30f;
    for (int c = 0; c < 3; ++c) {
        p.field_scale[c] = vf.scale[c];
        p.field_bias[c] = vf.bias[c];
    }
    p.field_scale[3] = 0.25f * r / vf.vmag_max; // peak warp = 25% radius
    p.field_bias[3] = vf.vmag_max;

    const std::vector<std::uint8_t> px = rime::viewer::render_warp_offscreen(*device,
                                                                             size,
                                                                             mesh,
                                                                             p,
                                                                             kClear,
                                                                             mesh_vert_spv,
                                                                             sizeof(mesh_vert_spv),
                                                                             mesh_frag_spv,
                                                                             sizeof(mesh_frag_spv),
                                                                             warp_vert_spv,
                                                                             sizeof(warp_vert_spv),
                                                                             warp_frag_spv,
                                                                             sizeof(warp_frag_spv),
                                                                             vf.rgba.data(),
                                                                             vf.nx,
                                                                             vf.ny,
                                                                             vf.nz);

    std::size_t lit = 0;
    for (std::size_t i = 0; i < static_cast<std::size_t>(size) * size; ++i)
        if (px[i * 4 + 0] > 40 || px[i * 4 + 1] > 40 || px[i * 4 + 2] > 40)
            ++lit;
    std::printf("icem_viewer: warped %u triangles by field '%s' — covers %.1f%% of a %ux%u frame\n",
                mesh.triangle_count(),
                vf.name.c_str(),
                100.0 * static_cast<double>(lit) / (static_cast<double>(size) * size),
                size,
                size);
    if (!write_ppm(out_path, px, size, size)) {
        std::fprintf(stderr, "icem_viewer: could not write '%s'\n", out_path.c_str());
        return 1;
    }
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Windowed warp: animate the surface by the vector field (a modal mode "breathes"), coloured by the
// field magnitude with a legend. M freezes/runs the animation.
bool run_warp_windowed(const CpuMesh& mesh,
                       rime::core::Vec3 world_up,
                       int max_frames,
                       const VectorField& vf) {
    using namespace rime::platform;
    if (!init())
        return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer (warp)";
    wd.width = 1280;
    wd.height = 720;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }
    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }

    const rime::rhi::Format depth_fmt = rime::rhi::Format::D32FloatS8;
    auto gpu = rime::viewer::make_mesh(*device,
                                       swapchain->format(),
                                       depth_fmt,
                                       mesh,
                                       mesh_vert_spv,
                                       sizeof(mesh_vert_spv),
                                       mesh_frag_spv,
                                       sizeof(mesh_frag_spv),
                                       vf.rgba.data(),
                                       vf.nx,
                                       vf.ny,
                                       vf.nz);
    rime::viewer::Warp warp = rime::viewer::make_warp(*device,
                                                      swapchain->format(),
                                                      depth_fmt,
                                                      warp_vert_spv,
                                                      sizeof(warp_vert_spv),
                                                      warp_frag_spv,
                                                      sizeof(warp_frag_spv));
    rime::viewer::Legend legend = rime::viewer::make_legend(*device,
                                                            swapchain->format(),
                                                            legend_vert_spv,
                                                            sizeof(legend_vert_spv),
                                                            legend_frag_spv,
                                                            sizeof(legend_frag_spv));
    rime::rhi::TextureHandle depth = make_depth(*device, swapchain->extent());

    OrbitCamera cam;
    {
        const rime::rhi::Extent2D e = swapchain->extent();
        setup_camera(
            cam, mesh, static_cast<float>(e.width) / static_cast<float>(e.height), world_up);
    }
    const float r = std::max(mesh.radius(), 1e-4f);
    const float amp = 0.25f * r; // peak displacement = 25% of the part radius
    const float freq = 0.6f;     // Hz

    std::printf(
        "icem_viewer: warping %u triangles by field '%s' (|max| %.4g) on '%s'.\n"
        "  camera: drag=orbit, right-drag=pan, wheel=zoom, F=reframe, ESC=quit; M=freeze/run\n",
        mesh.triangle_count(),
        vf.name.c_str(),
        static_cast<double>(vf.vmag_max),
        device->adapter().name.c_str());

    Input input;
    int frames = 0;
    bool animate = true;
    float phase = 0.0f; // seconds of animation accumulated (held when frozen)
    auto last = std::chrono::steady_clock::now();
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames)
            break;
        input.new_frame();
        Event e{};
        while (poll_event(e))
            input.process(e);
        if (input.key_pressed(Key::Escape))
            window->request_close();
        if (input.key_pressed(Key::M))
            animate = !animate;

        const auto now = std::chrono::steady_clock::now();
        const float dt = std::chrono::duration<float>(now - last).count();
        last = now;
        if (animate)
            phase += dt;

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float h = static_cast<float>(ext.height);
        const float aspect = static_cast<float>(ext.width) / h;
        if (input.mouse_down(MouseButton::Left))
            cam.orbit(input.mouse_dx() * 0.008f, -input.mouse_dy() * 0.008f);
        if (input.mouse_down(MouseButton::Right) || input.mouse_down(MouseButton::Middle))
            cam.pan(input.mouse_dx() / h, input.mouse_dy() / h);
        if (input.wheel_y() != 0.0f)
            cam.zoom(input.wheel_y());
        if (input.key_pressed(Key::F))
            cam.frame(mesh.center(), r, aspect);

        const float gain = (amp / vf.vmag_max) * std::sin(2.0f * 3.14159265f * freq * phase);
        MeshPush p{};
        p.mvp = cam.view_proj(aspect);
        const rime::core::Vec3 eye = cam.eye();
        p.cam_pos[0] = eye.x;
        p.cam_pos[1] = eye.y;
        p.cam_pos[2] = eye.z;
        p.cam_pos[3] = 1.0f;
        p.clip_plane[0] = p.clip_plane[1] = p.clip_plane[2] = 0.0f;
        p.clip_plane[3] = 1e30f;
        for (int c = 0; c < 3; ++c) {
            p.field_scale[c] = vf.scale[c];
            p.field_bias[c] = vf.bias[c];
        }
        p.field_scale[3] = gain;
        p.field_bias[3] = vf.vmag_max;

        rime::rhi::TextureHandle target = swapchain->acquire_next_image();
        if (!target.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
            continue;
        }
        auto cmd = device->begin_commands();
        rime::viewer::record_warp(*cmd, gpu, warp, target, depth, ext, p, kClear);
        rime::viewer::record_legend(*cmd, legend, target, ext);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
        }
        ++frames;
    }

    device->wait_idle();
    device->destroy(depth);
    rime::viewer::destroy_legend(*device, legend);
    rime::viewer::destroy_warp(*device, warp);
    rime::viewer::destroy_mesh(*device, gpu);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d warped frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

// Build the raymarch push: inverse view-projection (for per-pixel rays), the world→uvw affine, the
// isovalue + value range, step count, and the iso/DVR mode.
rime::viewer::IsoPush make_iso_push(const OrbitCamera& cam,
                                    float aspect,
                                    const ScalarField& sf,
                                    float isovalue,
                                    bool dvr) {
    rime::viewer::IsoPush p{};
    p.inv_vp = rime::core::inverse(cam.view_proj(aspect));
    for (int c = 0; c < 3; ++c) {
        p.field_scale[c] = sf.scale[c];
        p.field_bias[c] = sf.bias[c];
    }
    p.field_scale[3] = isovalue;
    p.field_bias[3] = sf.vmin;
    p.meta[0] = sf.vmax;
    p.meta[1] = 192.0f; // raymarch steps
    p.meta[2] = dvr ? 1.0f : 0.0f;
    return p;
}

// Off-screen isosurface/DVR snapshot.
int run_iso_offscreen(const CpuMesh& mesh,
                      const std::string& out_path,
                      std::uint32_t size,
                      rime::core::Vec3 world_up,
                      const ScalarField& sf,
                      float isovalue,
                      bool dvr) {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available\n");
        return 1;
    }
    OrbitCamera cam;
    setup_camera(cam, mesh, 1.0f, world_up);
    const std::vector<std::uint8_t> px =
        rime::viewer::render_iso_offscreen(*device,
                                           size,
                                           mesh,
                                           make_iso_push(cam, 1.0f, sf, isovalue, dvr),
                                           kClear,
                                           mesh_vert_spv,
                                           sizeof(mesh_vert_spv),
                                           mesh_frag_spv,
                                           sizeof(mesh_frag_spv),
                                           iso_vert_spv,
                                           sizeof(iso_vert_spv),
                                           iso_frag_spv,
                                           sizeof(iso_frag_spv),
                                           sf.rgba.data(),
                                           sf.nx,
                                           sf.ny,
                                           sf.nz);

    std::size_t lit = 0;
    for (std::size_t i = 0; i < static_cast<std::size_t>(size) * size; ++i)
        if (px[i * 4 + 0] > 40 || px[i * 4 + 1] > 40 || px[i * 4 + 2] > 40)
            ++lit;
    std::printf("icem_viewer: %s of '%s' at %.4g — covers %.1f%% of a %ux%u frame\n",
                dvr ? "DVR" : "isosurface",
                sf.name.c_str(),
                static_cast<double>(isovalue),
                100.0 * static_cast<double>(lit) / (static_cast<double>(size) * size),
                size,
                size);
    if (!write_ppm(out_path, px, size, size)) {
        std::fprintf(stderr, "icem_viewer: could not write '%s'\n", out_path.c_str());
        return 1;
    }
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Windowed isosurface: raymarch the scalar field; [ ] move the isovalue, V toggles DVR.
bool run_iso_windowed(const CpuMesh& mesh,
                      rime::core::Vec3 world_up,
                      int max_frames,
                      const ScalarField& sf,
                      float isovalue,
                      bool dvr) {
    using namespace rime::platform;
    if (!init())
        return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer (isosurface)";
    wd.width = 1280;
    wd.height = 720;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }
    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }

    auto gpu = rime::viewer::make_mesh(*device,
                                       swapchain->format(),
                                       rime::rhi::Format::D32Float,
                                       mesh,
                                       mesh_vert_spv,
                                       sizeof(mesh_vert_spv),
                                       mesh_frag_spv,
                                       sizeof(mesh_frag_spv),
                                       sf.rgba.data(),
                                       sf.nx,
                                       sf.ny,
                                       sf.nz);
    rime::viewer::Iso iso = rime::viewer::make_iso(*device,
                                                   swapchain->format(),
                                                   iso_vert_spv,
                                                   sizeof(iso_vert_spv),
                                                   iso_frag_spv,
                                                   sizeof(iso_frag_spv));
    rime::viewer::Legend legend = rime::viewer::make_legend(*device,
                                                            swapchain->format(),
                                                            legend_vert_spv,
                                                            sizeof(legend_vert_spv),
                                                            legend_frag_spv,
                                                            sizeof(legend_frag_spv));

    OrbitCamera cam;
    {
        const rime::rhi::Extent2D e = swapchain->extent();
        setup_camera(
            cam, mesh, static_cast<float>(e.width) / static_cast<float>(e.height), world_up);
    }
    const float step = std::max(sf.vmax - sf.vmin, 1e-6f) * 0.02f;
    std::printf("icem_viewer: raymarching field '%s' [%s] range %.4g .. %.4g on '%s'.\n"
                "  camera: drag=orbit, right-drag=pan, wheel=zoom, F=reframe, ESC=quit\n"
                "  isosurface: [ ]=move isovalue, V=toggle DVR (current iso %.4g)\n",
                sf.name.c_str(),
                sf.unit.c_str(),
                static_cast<double>(sf.vmin),
                static_cast<double>(sf.vmax),
                device->adapter().name.c_str(),
                static_cast<double>(isovalue));

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames)
            break;
        input.new_frame();
        Event e{};
        while (poll_event(e))
            input.process(e);
        if (input.key_pressed(Key::Escape))
            window->request_close();
        if (input.key_pressed(Key::V))
            dvr = !dvr;
        if (input.key_down(Key::LeftBracket))
            isovalue = std::max(sf.vmin, isovalue - step);
        if (input.key_down(Key::RightBracket))
            isovalue = std::min(sf.vmax, isovalue + step);

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float h = static_cast<float>(ext.height);
        const float aspect = static_cast<float>(ext.width) / h;
        if (input.mouse_down(MouseButton::Left))
            cam.orbit(input.mouse_dx() * 0.008f, -input.mouse_dy() * 0.008f);
        if (input.mouse_down(MouseButton::Right) || input.mouse_down(MouseButton::Middle))
            cam.pan(input.mouse_dx() / h, input.mouse_dy() / h);
        if (input.wheel_y() != 0.0f)
            cam.zoom(input.wheel_y());
        if (input.key_pressed(Key::F))
            cam.frame(mesh.center(), std::max(mesh.radius(), 1e-4f), aspect);

        rime::rhi::TextureHandle target = swapchain->acquire_next_image();
        if (!target.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            continue;
        }
        auto cmd = device->begin_commands();
        rime::viewer::record_iso(*cmd,
                                 iso,
                                 gpu.field_tex,
                                 gpu.field_sampler,
                                 target,
                                 ext,
                                 make_iso_push(cam, aspect, sf, isovalue, dvr),
                                 kClear);
        rime::viewer::record_legend(*cmd, legend, target, ext);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
        }
        ++frames;
    }

    device->wait_idle();
    rime::viewer::destroy_legend(*device, legend);
    rime::viewer::destroy_iso(*device, iso);
    rime::viewer::destroy_mesh(*device, gpu);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d isosurface frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

// Build a simple camera push (mvp + eye) for the line/flow passes.
MeshPush flow_push(const OrbitCamera& cam, float aspect) {
    MeshPush p{};
    p.mvp = cam.view_proj(aspect);
    const rime::core::Vec3 e = cam.eye();
    p.cam_pos[0] = e.x;
    p.cam_pos[1] = e.y;
    p.cam_pos[2] = e.z;
    p.cam_pos[3] = 1.0f;
    return p;
}

// Off-screen streamlines snapshot.
int run_flow_offscreen(const CpuMesh& mesh,
                       const std::string& out_path,
                       std::uint32_t size,
                       rime::core::Vec3 world_up,
                       const VectorField& vf) {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available\n");
        return 1;
    }
    OrbitCamera cam;
    setup_camera(cam, mesh, 1.0f, world_up);
    const std::vector<std::uint8_t> px =
        rime::viewer::render_streamlines_offscreen(*device,
                                                   size,
                                                   vf,
                                                   flow_push(cam, 1.0f),
                                                   kClear,
                                                   streamline_vert_spv,
                                                   sizeof(streamline_vert_spv),
                                                   streamline_frag_spv,
                                                   sizeof(streamline_frag_spv));
    std::size_t lit = 0;
    for (std::size_t i = 0; i < static_cast<std::size_t>(size) * size; ++i)
        if (px[i * 4 + 0] > 40 || px[i * 4 + 1] > 40 || px[i * 4 + 2] > 40)
            ++lit;
    std::printf("icem_viewer: streamlines of '%s' — cover %.1f%% of a %ux%u frame\n",
                vf.name.c_str(),
                100.0 * static_cast<double>(lit) / (static_cast<double>(size) * size),
                size,
                size);
    if (!write_ppm(out_path, px, size, size))
        return 1;
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Windowed streamlines: orbit the computed flow, lines coloured by speed, with the legend.
bool run_flow_windowed(const CpuMesh& mesh,
                       rime::core::Vec3 world_up,
                       int max_frames,
                       const VectorField& vf) {
    using namespace rime::platform;
    if (!init())
        return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer (flow)";
    wd.width = 1280;
    wd.height = 720;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }
    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }

    const std::vector<float> verts = rime::viewer::build_streamlines(vf);
    rime::viewer::StreamlineView flow =
        rime::viewer::make_streamlines(*device,
                                       swapchain->format(),
                                       rime::rhi::Format::D32FloatS8,
                                       streamline_vert_spv,
                                       sizeof(streamline_vert_spv),
                                       streamline_frag_spv,
                                       sizeof(streamline_frag_spv),
                                       verts);
    rime::viewer::Legend legend = rime::viewer::make_legend(*device,
                                                            swapchain->format(),
                                                            legend_vert_spv,
                                                            sizeof(legend_vert_spv),
                                                            legend_frag_spv,
                                                            sizeof(legend_frag_spv));
    rime::rhi::TextureHandle depth = make_depth(*device, swapchain->extent());

    OrbitCamera cam;
    {
        const rime::rhi::Extent2D e = swapchain->extent();
        setup_camera(
            cam, mesh, static_cast<float>(e.width) / static_cast<float>(e.height), world_up);
    }
    std::printf("icem_viewer: %u streamline segments of field '%s' (|u|max %.4g) on '%s'.\n"
                "  camera: drag=orbit, right-drag=pan, wheel=zoom, F=reframe, ESC=quit\n",
                flow.vertex_count / 2,
                vf.name.c_str(),
                static_cast<double>(vf.vmag_max),
                device->adapter().name.c_str());

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames)
            break;
        input.new_frame();
        Event e{};
        while (poll_event(e))
            input.process(e);
        if (input.key_pressed(Key::Escape))
            window->request_close();

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float hh = static_cast<float>(ext.height);
        const float aspect = static_cast<float>(ext.width) / hh;
        if (input.mouse_down(MouseButton::Left))
            cam.orbit(input.mouse_dx() * 0.008f, -input.mouse_dy() * 0.008f);
        if (input.mouse_down(MouseButton::Right) || input.mouse_down(MouseButton::Middle))
            cam.pan(input.mouse_dx() / hh, input.mouse_dy() / hh);
        if (input.wheel_y() != 0.0f)
            cam.zoom(input.wheel_y());
        if (input.key_pressed(Key::F))
            cam.frame(mesh.center(), std::max(mesh.radius(), 1e-4f), aspect);

        rime::rhi::TextureHandle target = swapchain->acquire_next_image();
        if (!target.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
            continue;
        }
        auto cmd = device->begin_commands();
        rime::viewer::record_streamlines(
            *cmd, flow, target, depth, ext, flow_push(cam, aspect), kClear);
        rime::viewer::record_legend(*cmd, legend, target, ext);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
        }
        ++frames;
    }

    device->wait_idle();
    device->destroy(depth);
    rime::viewer::destroy_legend(*device, legend);
    rime::viewer::destroy_streamlines(*device, flow);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d flow frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

// ---- Assemblies (E1): many parts, per-part colour + visibility, exploded view ----

// List the parts on the console so the number-key toggles make sense. (A real on-screen UI — text,
// clickable rows — is E2; until then the "legend" lives here.)
void print_assembly(const rime::viewer::Assembly& a) {
    std::printf("icem_viewer: assembly of %zu parts —\n", a.parts.size());
    for (std::size_t i = 0; i < a.parts.size(); ++i)
        std::printf("    %zu  %-18s  rgb(%.2f %.2f %.2f)\n",
                    i + 1,
                    a.parts[i].name.c_str(),
                    static_cast<double>(a.parts[i].color.x),
                    static_cast<double>(a.parts[i].color.y),
                    static_cast<double>(a.parts[i].color.z));
}

// Aim the camera at the (possibly exploded) assembly: frame its enclosing sphere at this explode
// factor.
void frame_assembly(OrbitCamera& cam,
                    const rime::viewer::Assembly& a,
                    float aspect,
                    float factor,
                    rime::core::Vec3 world_up) {
    const float r = rime::viewer::framing_radius(a, factor);
    cam.world_up = world_up;
    cam.z_near = std::max(r * 0.02f, 1e-4f);
    cam.z_far = r * 100.0f + 10.0f;
    cam.min_distance = r * 0.02f;
    cam.max_distance = r * 100.0f;
    cam.frame(a.center, r, aspect);
    cam.yaw = rime::core::radians(35.0f);
    cam.pitch = rime::core::radians(20.0f);
}

// The on-screen control panel (E2): a from-scratch UI panel pinned at the top-left.
constexpr float kPanelX = 12.0f, kPanelY = 12.0f, kPanelW = 230.0f;

// Lay out the assembly control panel and apply its widgets to the assembly — a title, a reset-view
// button, an explode slider (0–100 %), and one checkbox per part bound to its visibility. Returns
// the panel height (so the caller knows when the cursor is over the UI). Shared by the windowed
// panel and the off-screen snapshot's overlay, so both read identically.
float build_assembly_panel(rime::viewer::ui::Ui& ui,
                           rime::viewer::Assembly& a,
                           float& explode_pct,
                           bool& reframe) {
    const float ph = 18.0f + (3.0f + static_cast<float>(a.parts.size())) * 30.0f;
    ui.panel(kPanelX, kPanelY, kPanelW, ph);
    ui.label("ICEM VIEWER");
    if (ui.button("RESET VIEW"))
        reframe = true;
    ui.slider("EXPLODE %", explode_pct, 0.0f, 100.0f);
    for (rime::viewer::Part& p : a.parts)
        ui.checkbox(p.name, p.visible);
    return ph;
}

// Off-screen assembly snapshot, with the control panel drawn over it (so the screenshot shows both
// the coloured machine and the from-scratch UI).
int run_assembly_offscreen(rime::viewer::Assembly& a,
                           const std::string& out_path,
                           std::uint32_t size,
                           rime::core::Vec3 world_up,
                           float factor) {
    using namespace rime::rhi;
    DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available\n");
        return 1;
    }
    OrbitCamera cam;
    frame_assembly(cam, a, 1.0f, factor, world_up);

    rime::viewer::AssemblyGpu gpu = rime::viewer::make_assembly_gpu(*device,
                                                                    Format::RGBA8Unorm,
                                                                    Format::D32Float,
                                                                    a,
                                                                    mesh_vert_spv,
                                                                    sizeof(mesh_vert_spv),
                                                                    mesh_frag_spv,
                                                                    sizeof(mesh_frag_spv));
    rime::viewer::ui::UiRenderer uir = rime::viewer::ui::make_ui_renderer(*device,
                                                                          Format::RGBA8Unorm,
                                                                          ui_vert_spv,
                                                                          sizeof(ui_vert_spv),
                                                                          ui_frag_spv,
                                                                          sizeof(ui_frag_spv));

    rime::viewer::ui::Ui gui;
    float explode_pct = factor * 100.0f;
    bool reframe = false;
    gui.begin(static_cast<float>(size), static_cast<float>(size), -1.0f, -1.0f, false);
    build_assembly_panel(gui, a, explode_pct, reframe);
    gui.end();
    rime::viewer::ui::upload_ui(*device, uir, gui);

    TextureDesc ctd{};
    ctd.extent = {size, size};
    ctd.format = Format::RGBA8Unorm;
    ctd.usage = TextureUsage::ColorAttachment | TextureUsage::TransferSrc;
    const TextureHandle color = device->create_texture(ctd);
    TextureDesc dtd{};
    dtd.extent = {size, size};
    dtd.format = Format::D32Float;
    dtd.usage = TextureUsage::DepthStencil;
    const TextureHandle depth = device->create_texture(dtd);
    const std::uint64_t byte_count = static_cast<std::uint64_t>(size) * size * 4;
    BufferDesc rbd{};
    rbd.size = byte_count;
    rbd.usage = BufferUsage::TransferDst;
    rbd.memory = MemoryUsage::GpuToCpu;
    const BufferHandle readback = device->create_buffer(rbd);

    auto cmd = device->begin_commands();
    rime::viewer::record_assembly(
        *cmd, gpu, a, color, depth, {size, size}, cam.view_proj(1.0f), cam.eye(), factor, kClear);
    rime::viewer::ui::record_ui(*cmd, uir, color, {size, size});
    cmd->copy_texture_to_buffer(color, readback);
    device->submit_blocking(*cmd);

    std::vector<std::uint8_t> px(byte_count);
    device->read_buffer(readback, px.data(), px.size(), 0);
    device->destroy(readback);
    device->destroy(depth);
    device->destroy(color);
    rime::viewer::ui::destroy_ui_renderer(*device, uir);
    rime::viewer::destroy_assembly_gpu(*device, gpu);

    std::size_t lit = 0;
    for (std::size_t i = 0; i < static_cast<std::size_t>(size) * size; ++i)
        if (px[i * 4 + 0] > 40 || px[i * 4 + 1] > 40 || px[i * 4 + 2] > 40)
            ++lit;
    std::printf("icem_viewer: %zu of %zu parts visible%s — covers %.1f%% of a %ux%u frame\n",
                a.visible_count(),
                a.parts.size(),
                factor > 0.01f ? " (exploded)" : "",
                100.0 * static_cast<double>(lit) / (static_cast<double>(size) * size),
                size,
                size);
    if (!write_ppm(out_path, px, size, size)) {
        std::fprintf(stderr, "icem_viewer: could not write '%s'\n", out_path.c_str());
        return 1;
    }
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Windowed assembly: orbit the machine; a from-scratch control panel (E2) toggles parts and drives
// the explode slider; the number keys / E still work too.
bool run_assembly_windowed(rime::viewer::Assembly& a,
                           rime::core::Vec3 world_up,
                           int max_frames,
                           float explode_target) {
    using namespace rime::platform;
    if (!init())
        return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer (assembly)";
    wd.width = 1280;
    wd.height = 720;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }
    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }

    rime::viewer::AssemblyGpu gpu = rime::viewer::make_assembly_gpu(*device,
                                                                    swapchain->format(),
                                                                    rime::rhi::Format::D32FloatS8,
                                                                    a,
                                                                    mesh_vert_spv,
                                                                    sizeof(mesh_vert_spv),
                                                                    mesh_frag_spv,
                                                                    sizeof(mesh_frag_spv));
    rime::rhi::TextureHandle depth = make_depth(*device, swapchain->extent());
    rime::viewer::ui::UiRenderer uir = rime::viewer::ui::make_ui_renderer(*device,
                                                                          swapchain->format(),
                                                                          ui_vert_spv,
                                                                          sizeof(ui_vert_spv),
                                                                          ui_frag_spv,
                                                                          sizeof(ui_frag_spv));
    rime::viewer::ui::Ui gui;

    OrbitCamera cam;
    {
        const rime::rhi::Extent2D e = swapchain->extent();
        frame_assembly(
            cam, a, static_cast<float>(e.width) / static_cast<float>(e.height), 0.0f, world_up);
    }
    print_assembly(a);
    std::printf(
        "  panel: click a part's checkbox to show/hide it, drag EXPLODE, RESET VIEW to reframe\n"
        "  camera: drag=orbit, right-drag=pan, wheel=zoom, F=reframe, ESC=quit\n"
        "  keys also: 1-9/0 toggle a part, E explode/collapse, A show all parts\n"
        "  rendering on '%s'.\n",
        device->adapter().name.c_str());

    const Key digit[10] = {Key::Num1,
                           Key::Num2,
                           Key::Num3,
                           Key::Num4,
                           Key::Num5,
                           Key::Num6,
                           Key::Num7,
                           Key::Num8,
                           Key::Num9,
                           Key::Num0};
    float factor = 0.0f;
    float explode_pct = explode_target * 100.0f;

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames)
            break;
        input.new_frame();
        Event e{};
        while (poll_event(e))
            input.process(e);
        if (input.key_pressed(Key::Escape))
            window->request_close();
        if (input.key_pressed(Key::E))
            explode_pct = (explode_pct > 50.0f) ? 0.0f : 100.0f;
        if (input.key_pressed(Key::A))
            for (rime::viewer::Part& p : a.parts)
                p.visible = true;
        for (int d = 0; d < 10; ++d)
            if (input.key_pressed(digit[d]) && static_cast<std::size_t>(d) < a.parts.size())
                a.parts[d].visible = !a.parts[d].visible;

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float hh = static_cast<float>(ext.height);
        const float aspect = static_cast<float>(ext.width) / hh;

        // Build + apply the control panel this frame, then learn whether the cursor is over it (so
        // the camera ignores clicks that belong to a widget — including an in-progress slider
        // drag).
        const float mx = input.mouse_x(), my = input.mouse_y();
        gui.begin(static_cast<float>(ext.width),
                  static_cast<float>(ext.height),
                  mx,
                  my,
                  input.mouse_down(MouseButton::Left));
        bool reframe = input.key_pressed(Key::F);
        const float ph = build_assembly_panel(gui, a, explode_pct, reframe);
        gui.end();
        const bool over_ui = gui.is_active() || (mx >= kPanelX && mx <= kPanelX + kPanelW &&
                                                 my >= kPanelY && my <= kPanelY + ph);

        // Ease the explode factor toward the slider / E key.
        factor += std::clamp(explode_pct / 100.0f - factor, -0.04f, 0.04f);
        if (!over_ui && input.mouse_down(MouseButton::Left))
            cam.orbit(input.mouse_dx() * 0.008f, -input.mouse_dy() * 0.008f);
        if (!over_ui &&
            (input.mouse_down(MouseButton::Right) || input.mouse_down(MouseButton::Middle)))
            cam.pan(input.mouse_dx() / hh, input.mouse_dy() / hh);
        if (!over_ui && input.wheel_y() != 0.0f)
            cam.zoom(input.wheel_y());
        if (reframe)
            cam.frame(a.center, rime::viewer::framing_radius(a, factor), aspect);

        rime::rhi::TextureHandle tgt = swapchain->acquire_next_image();
        if (!tgt.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
            continue;
        }
        rime::viewer::ui::upload_ui(*device, uir, gui);
        auto cmd = device->begin_commands();
        rime::viewer::record_assembly(
            *cmd, gpu, a, tgt, depth, ext, cam.view_proj(aspect), cam.eye(), factor, kClear);
        rime::viewer::ui::record_ui(*cmd, uir, tgt, ext);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
        }
        ++frames;
    }

    device->wait_idle();
    device->destroy(depth);
    rime::viewer::ui::destroy_ui_renderer(*device, uir);
    rime::viewer::destroy_assembly_gpu(*device, gpu);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d assembly frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

// ---- Provenance (E3): surface ICEM's "why" Ledger on the from-scratch UI ----

// Off-screen provenance snapshot — the panel with the verdict node's derivation expanded.
int run_provenance_offscreen(const rime::viewer::Provenance& prov,
                             const std::string& out_path,
                             std::uint32_t size) {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available\n");
        return 1;
    }
    rime::viewer::ui::Ui gui;
    int selected = prov.nodes.empty() ? -1 : static_cast<int>(prov.nodes.size()) - 1; // the verdict
    gui.begin(static_cast<float>(size), static_cast<float>(size), -1.0f, -1.0f, false);
    build_provenance_panel(gui, prov, selected, 0.0f, static_cast<float>(size), static_cast<float>(size));
    gui.end();
    const rime::rhi::ClearColor clear{0.06f, 0.07f, 0.09f, 1.0f};
    const std::vector<std::uint8_t> px = rime::viewer::ui::render_ui_offscreen(
        *device, size, gui, clear, ui_vert_spv, sizeof(ui_vert_spv), ui_frag_spv, sizeof(ui_frag_spv));
    std::printf("icem_viewer: provenance of '%s' — %zu nodes, verdict %s\n",
                prov.design.c_str(),
                prov.nodes.size(),
                prov.passes ? "PASS" : "FAIL");
    if (!write_ppm(out_path, px, size, size)) {
        std::fprintf(stderr, "icem_viewer: could not write '%s'\n", out_path.c_str());
        return 1;
    }
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Windowed provenance: click a value to expand its derivation, the wheel scrolls the ledger.
bool run_provenance_windowed(const rime::viewer::Provenance& prov, int max_frames) {
    using namespace rime::platform;
    if (!init()) return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer (provenance)";
    wd.width = 1100;
    wd.height = 820;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }
    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }
    rime::viewer::ui::UiRenderer uir =
        rime::viewer::ui::make_ui_renderer(*device, swapchain->format(), ui_vert_spv,
                                           sizeof(ui_vert_spv), ui_frag_spv, sizeof(ui_frag_spv));
    rime::viewer::ui::Ui gui;
    int selected = -1;
    float scroll = 0.0f, content = 0.0f;
    std::printf("icem_viewer: provenance '%s' (%zu nodes) — click a value to see why, wheel scrolls, "
                "ESC quits. On '%s'.\n",
                prov.design.c_str(),
                prov.nodes.size(),
                device->adapter().name.c_str());

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames) break;
        input.new_frame();
        Event e{};
        while (poll_event(e)) input.process(e);
        if (input.key_pressed(Key::Escape)) window->request_close();

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float W = static_cast<float>(ext.width), H = static_cast<float>(ext.height);
        if (input.wheel_y() != 0.0f) scroll -= input.wheel_y() * 40.0f;
        scroll = std::clamp(scroll, 0.0f, std::max(0.0f, content - (H - 86.0f)));

        gui.begin(W, H, input.mouse_x(), input.mouse_y(), input.mouse_down(MouseButton::Left));
        content = build_provenance_panel(gui, prov, selected, scroll, W, H);
        gui.end();

        rime::rhi::TextureHandle tgt = swapchain->acquire_next_image();
        if (!tgt.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            continue;
        }
        rime::viewer::ui::upload_ui(*device, uir, gui);
        auto cmd = device->begin_commands();
        rime::viewer::ui::record_ui(*cmd, uir, tgt, ext, rime::rhi::LoadOp::Clear, kClear);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
        }
        ++frames;
    }

    device->wait_idle();
    rime::viewer::ui::destroy_ui_renderer(*device, uir);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d provenance frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

} // namespace

int main(int argc, char** argv) {
    std::string stl_path;
    std::string field_path; // explicit --field; else a sibling <stem>.icef is tried
    std::string out_path = "icem_view.ppm";
    bool offscreen = false;
    bool no_field = false;
    bool no_cap = false;
    bool warp_mode = false; // --warp: animate the surface by a vec3 field (C3)
    std::string warp_name;  // optional vec3 field name to warp by (else the first vec3 field)
    bool flow_mode = false; // --flow: streamlines of a vec3 velocity field (D)
    std::string flow_name;  // optional vec3 velocity field name (else the first vec3 field)
    bool iso_mode = false;  // --iso: raymarched isosurface of a scalar field (C2)
    bool iso_given = false;
    float iso_value = 0.0f;
    bool dvr = false; // --dvr: direct volume rendering instead of an isosurface
    bool speed_mode =
        false; // --speed: colour/iso/DVR the scalar speed |v| of a vec3 velocity field (D2)
    std::string speed_name; // optional vec3 velocity field name (else the first vec3 field)
    std::string
        assembly_dir;     // --assembly <dir>: load every *.stl as a coloured, toggleable part (E1)
    bool explode = false; // --explode [factor]: start the assembly view exploded
    float explode_factor = 1.0f;
    bool prov_mode = false; // --provenance: show ICEM's "why" Ledger (.icejson) on the UI (E3)
    std::string prov_path;  // explicit .icejson path; else provenance.icejson / an STL sibling is tried
    bool turntable = false; // --turntable [N]: render a full 360° orbit to N numbered PPM frames (E4)
    int turntable_frames = 72; // default 72 frames = one every 5°
    std::uint32_t size = 512;
    int frames = 0;
    rime::core::Vec3 world_up{0.0f, 0.0f, 1.0f}; // ICEM parts are authored z-up
    Clip clip; // off unless --clip is given (offscreen); the window toggles it interactively

    for (int i = 1; i < argc; ++i) {
        const std::string_view a(argv[i]);
        if (a == "--offscreen" || a == "--headless") {
            offscreen = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                out_path = argv[++i];
        } else if (a == "--windowed") {
            offscreen = false;
        } else if (a == "--field" && i + 1 < argc) {
            field_path = argv[++i];
        } else if (a == "--no-field") {
            no_field = true;
        } else if (a == "--no-cap") {
            no_cap = true;
        } else if (a == "--warp") {
            warp_mode = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                warp_name = argv[++i];
        } else if (a == "--flow") {
            flow_mode = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                flow_name = argv[++i];
        } else if (a == "--iso") {
            iso_mode = true;
            if (i + 1 < argc && argv[i + 1][0] != '-') {
                iso_value = static_cast<float>(std::atof(argv[++i]));
                iso_given = true;
            }
        } else if (a == "--dvr") {
            iso_mode = true;
            dvr = true;
        } else if (a == "--speed") {
            speed_mode = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                speed_name = argv[++i];
        } else if (a == "--assembly") {
            assembly_dir = (i + 1 < argc && argv[i + 1][0] != '-') ? argv[++i] : ".";
        } else if (a == "--explode") {
            explode = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                explode_factor = static_cast<float>(std::atof(argv[++i]));
        } else if (a == "--provenance") {
            prov_mode = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                prov_path = argv[++i];
        } else if (a == "--turntable") {
            turntable = true;
            if (i + 1 < argc && argv[i + 1][0] != '-')
                turntable_frames = std::max(1, std::atoi(argv[++i]));
        } else if (a == "--clip" && i + 1 < argc) {
            const std::string_view ax(argv[++i]);
            clip.on = true;
            clip.axis = (ax == "y") ? 1 : (ax == "z") ? 2 : 0;
        } else if (a == "--size" && i + 1 < argc) {
            size = static_cast<std::uint32_t>(std::max(8, std::atoi(argv[++i])));
        } else if (a == "--frames" && i + 1 < argc) {
            frames = std::atoi(argv[++i]);
        } else if (a == "--up-y") {
            world_up = {0.0f, 1.0f, 0.0f};
        } else if (!a.empty() && a[0] != '-') {
            stl_path = a;
        }
    }

    // --provenance: surface ICEM's "why" Ledger (.icejson) on the from-scratch UI (E3). A panel-only
    // view — no 3-D mesh — so it dispatches before any STL/assembly loading. The file is an explicit
    // --provenance <path>, else `provenance.icejson` (what `icem provenance <dir>` writes), else an
    // STL sibling <stem>.icejson.
    if (prov_mode) {
        std::string ppath = prov_path;
        if (ppath.empty())
            ppath = stl_path.empty() ? "provenance.icejson" : replace_extension(stl_path, ".icejson");
        auto prov = rime::viewer::load_provenance(ppath);
        if (!prov) {
            std::fprintf(stderr,
                         "icem_viewer: could not load ICEM provenance '%s' "
                         "(generate one with `icem provenance <dir>`)\n",
                         ppath.c_str());
            return 1;
        }
        if (offscreen)
            return run_provenance_offscreen(*prov, out_path, size);
        if (run_provenance_windowed(*prov, frames))
            return 0;
        return run_provenance_offscreen(*prov, out_path, size);
    }

    // --assembly <dir> (or a directory passed as the positional path): load every *.stl in it as a
    // coloured, individually toggleable part and show them together, with an exploded view (E1).
    {
        std::error_code ec;
        if (assembly_dir.empty() && !stl_path.empty() &&
            std::filesystem::is_directory(stl_path, ec))
            assembly_dir = stl_path;
    }
    if (!assembly_dir.empty()) {
        auto assembly = rime::viewer::load_assembly(assembly_dir);
        if (!assembly) {
            std::fprintf(
                stderr, "icem_viewer: no loadable STL parts in '%s'\n", assembly_dir.c_str());
            return 1;
        }
        const float factor = explode ? explode_factor : 0.0f;
        if (offscreen)
            return run_assembly_offscreen(*assembly, out_path, size, world_up, factor);
        if (run_assembly_windowed(*assembly, world_up, frames, factor))
            return 0;
        return run_assembly_offscreen(*assembly, out_path, size, world_up, factor);
    }

    CpuMesh mesh;
    if (!stl_path.empty()) {
        auto loaded = rime::viewer::load_stl_binary_file(stl_path);
        if (!loaded) {
            std::fprintf(stderr, "icem_viewer: could not load binary STL '%s'\n", stl_path.c_str());
            return 1;
        }
        mesh = std::move(*loaded);
    } else {
        std::printf(
            "icem_viewer: no STL given — showing a unit cube. Pass a binary STL to view a part.\n");
        mesh = rime::viewer::make_unit_cube();
    }

    // --warp: animate the surface by a computed vec3 field (displacement / modal mode shape). It
    // reads the same .icef (explicit --field, else the STL's sibling), picking a vector field by
    // name.
    if (warp_mode) {
        const std::string vpath = field_path.empty() ? sibling_icef(stl_path) : field_path;
        auto vfield = rime::viewer::load_icef_vector(vpath, warp_name);
        if (!vfield) {
            std::fprintf(
                stderr,
                "icem_viewer: --warp needs a vec3 field in '%s' (e.g. displacement or mode1)\n",
                vpath.c_str());
            return 1;
        }
        std::printf("icem_viewer: warp field '%s' [%s] |max| %.4g on a %ux%ux%u grid (%s)\n",
                    vfield->name.c_str(),
                    vfield->unit.c_str(),
                    static_cast<double>(vfield->vmag_max),
                    vfield->nx,
                    vfield->ny,
                    vfield->nz,
                    vpath.c_str());
        if (offscreen)
            return run_warp_offscreen(mesh, out_path, size, world_up, *vfield);
        if (run_warp_windowed(mesh, world_up, frames, *vfield))
            return 0;
        return run_warp_offscreen(mesh, out_path, size, world_up, *vfield);
    }

    // --flow: streamlines of a computed 3-D velocity field (ICEM's potential-flow .icef, brick24).
    if (flow_mode) {
        const std::string vpath = field_path.empty() ? sibling_icef(stl_path) : field_path;
        auto vfield = rime::viewer::load_icef_vector(vpath, flow_name);
        if (!vfield) {
            std::fprintf(
                stderr, "icem_viewer: --flow needs a vec3 velocity field in '%s'\n", vpath.c_str());
            return 1;
        }
        std::printf("icem_viewer: flow field '%s' [%s] |u|max %.4g on a %ux%ux%u grid (%s)\n",
                    vfield->name.c_str(),
                    vfield->unit.c_str(),
                    static_cast<double>(vfield->vmag_max),
                    vfield->nx,
                    vfield->ny,
                    vfield->nz,
                    vpath.c_str());
        if (offscreen)
            return run_flow_offscreen(mesh, out_path, size, world_up, *vfield);
        if (run_flow_windowed(mesh, world_up, frames, *vfield))
            return 0;
        return run_flow_offscreen(mesh, out_path, size, world_up, *vfield);
    }

    // A scalar field for the colormap / legend / isosurface / DVR: either a scalar straight from
    // the .icef, or — with --speed — the magnitude |v| derived from a vec3 velocity field (D2·V),
    // so the viscous boundary layer can be shown as a coloured surface, isotach or DVR volume, not
    // only as lines.
    const auto load_scalar = [&](const std::string& path) -> std::optional<ScalarField> {
        if (speed_mode) {
            auto vf = rime::viewer::load_icef_vector(path, speed_name);
            if (!vf)
                return std::nullopt;
            return rime::viewer::speed_field(*vf);
        }
        return rime::viewer::load_icef_scalar(path);
    };

    // --iso / --dvr: GPU raymarched isosurface or DVR of a scalar field (C2; or the speed scalar,
    // D2·V).
    if (iso_mode) {
        const std::string spath = field_path.empty() ? sibling_icef(stl_path) : field_path;
        auto sf = load_scalar(spath);
        if (!sf) {
            std::fprintf(stderr,
                         "icem_viewer: --iso needs a %s in '%s'\n",
                         speed_mode ? "vec3 velocity field (--speed)" : "scalar field",
                         spath.c_str());
            return 1;
        }
        const float iso = iso_given ? iso_value : 0.5f * (sf->vmin + sf->vmax);
        std::printf("icem_viewer: %s field '%s' [%s] range %.4g .. %.4g, iso %.4g (%s)\n",
                    dvr ? "DVR of" : "isosurface of",
                    sf->name.c_str(),
                    sf->unit.c_str(),
                    static_cast<double>(sf->vmin),
                    static_cast<double>(sf->vmax),
                    static_cast<double>(iso),
                    spath.c_str());
        if (offscreen)
            return run_iso_offscreen(mesh, out_path, size, world_up, *sf, iso, dvr);
        if (run_iso_windowed(mesh, world_up, frames, *sf, iso, dvr))
            return 0;
        return run_iso_offscreen(mesh, out_path, size, world_up, *sf, iso, dvr);
    }

    // Load a simulation field: an explicit --field path, else the STL's sibling <stem>.icef if
    // present.
    std::optional<ScalarField> field;
    const bool explicit_field = !field_path.empty();
    if (field_path.empty())
        field_path = sibling_icef(stl_path);
    if (!field_path.empty()) {
        field = load_scalar(field_path);
        if (field) {
            std::printf(
                "icem_viewer: loaded field '%s' [%s] range %.4g .. %.4g on a %ux%ux%u grid (%s)\n",
                field->name.c_str(),
                field->unit.c_str(),
                static_cast<double>(field->vmin),
                static_cast<double>(field->vmax),
                field->nx,
                field->ny,
                field->nz,
                field_path.c_str());
        } else if (explicit_field) {
            std::fprintf(stderr, "icem_viewer: could not load field '%s'\n", field_path.c_str());
        }
    }

    const ScalarField* fptr = field ? &*field : nullptr;
    const bool field_on = field.has_value() && !no_field;
    const bool cap_on = !no_cap;

    // --turntable: a headless 360° orbit to a numbered PPM sequence (honours --clip / --field), no
    // window. Dispatched before the windowed/offscreen single-shot since it is its own export mode.
    if (turntable)
        return run_turntable_offscreen(
            mesh, out_path, size, world_up, clip, fptr, field_on, cap_on, turntable_frames);

    if (offscreen)
        return run_offscreen(mesh, out_path, size, world_up, clip, fptr, field_on, cap_on);
    if (run_windowed(mesh, world_up, frames, fptr, field_on, cap_on))
        return 0;
    std::printf("icem_viewer: no window/display — falling back to off-screen (%s).\n",
                out_path.c_str());
    return run_offscreen(mesh, out_path, size, world_up, clip, fptr, field_on, cap_on);
}
