// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 The Rime Engine Authors.
//
// 03-icem-viewer — the ICEM viewer. It loads a computed part (a binary STL, e.g. ICEM's brick6 thrust
// chamber) and draws it depth-correct and lit, orbitable with the mouse; cuts a cross-section to see
// inside it (B2); and, when a computed simulation field is supplied (ICEM's .icef, e.g. the brick23
// temperature field), colours the part — and the interior the cut reveals — by that field with a
// colormap + legend (C1). Two modes, like the other samples:
//   * windowed (default): present via the swapchain — drag to orbit, right-drag to pan, wheel to zoom,
//     F to reframe, C to toggle the section, G to toggle the field colormap, ESC to quit;
//   * off-screen (--offscreen [file.ppm]): render one frame to a file (and print coverage) — runnable
//     anywhere, GPU-free in CI. tests/rhi/mesh_offscreen_test asserts on this exact render.
//
// Run it:   build/dev/bin/icem_viewer field.stl --field field.icef   # part coloured by the field
//           build/dev/bin/icem_viewer field.stl                      # auto-loads sibling field.icef
//           build/dev/bin/icem_viewer part.stl --offscreen view.ppm --clip z --field field.icef
//           build/dev/bin/icem_viewer            # no file → a unit cube, so it runs out of the box

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "rime/platform/platform.hpp"
#include "rime/rhi/rhi.hpp"

#include "camera.hpp"
#include "field.hpp"
#include "legend.hpp"
#include "mesh_render.hpp"
#include "stl.hpp"

// Generated by rime_add_shaders from shaders/*.{vert,frag} (ADR-0008, offline compile).
#include "legend.frag.spv.h"
#include "legend.vert.spv.h"
#include "mesh.frag.spv.h"
#include "mesh.vert.spv.h"

namespace {

using rime::viewer::CpuMesh;
using rime::viewer::MeshPush;
using rime::viewer::OrbitCamera;
using rime::viewer::ScalarField;

constexpr rime::rhi::ClearColor kClear{0.08f, 0.09f, 0.11f, 1.0f}; // dark studio background

// Point the camera at the part: frame its bounding sphere, set near/far to bracket it, and start from
// a pleasant three-quarter view. ICEM authors parts z-up (cylinders/revolves about z), so that is the
// default orbit axis.
void setup_camera(OrbitCamera& cam, const CpuMesh& mesh, float aspect, rime::core::Vec3 world_up) {
    const float r = std::max(mesh.radius(), 1e-4f);
    cam.world_up = world_up;
    cam.z_near = std::max(r * 0.02f, 1e-4f);
    cam.z_far = r * 100.0f + 10.0f;
    cam.min_distance = r * 0.05f;
    cam.max_distance = r * 100.0f;
    cam.frame(mesh.center(), r, aspect);
    cam.yaw = rime::core::radians(35.0f);
    cam.pitch = rime::core::radians(20.0f);
}

// Interactive cross-section state: a world-axis-aligned plane that cuts the part open. `axis` picks
// the plane normal (x/y/z), `sign` which half is removed, `offset` where along the axis the plane sits.
struct Clip {
    bool on = false;
    int axis = 0;        // 0 = x, 1 = y, 2 = z
    float sign = 1.0f;   // +1 removes the +axis half, -1 the −axis half
    float offset = 0.0f; // plane position along the axis, in world units
};

rime::core::Vec3 axis_unit(int axis) {
    return axis == 0 ? rime::core::Vec3{1, 0, 0}
         : axis == 1 ? rime::core::Vec3{0, 1, 0}
                     : rime::core::Vec3{0, 0, 1};
}

// Fill the field colormap push params from a loaded field, or zero them (which the shader reads as
// "no field": it shades the neutral metal albedo). The field is "on" iff vmax > vmin.
void set_field_push(MeshPush& p, const ScalarField* field, bool on) {
    if (field && on) {
        for (int c = 0; c < 3; ++c) {
            p.field_scale[c] = field->scale[c];
            p.field_bias[c] = field->bias[c];
        }
        p.field_scale[3] = field->vmin;
        p.field_bias[3] = field->vmax;
    } else {
        p.field_scale[0] = p.field_scale[1] = p.field_scale[2] = p.field_scale[3] = 0.0f;
        p.field_bias[0] = p.field_bias[1] = p.field_bias[2] = p.field_bias[3] = 0.0f;
    }
}

MeshPush make_push(const OrbitCamera& cam, float aspect, const Clip& clip, const ScalarField* field,
                   bool field_on) {
    MeshPush p{};
    p.mvp = cam.view_proj(aspect);
    const rime::core::Vec3 e = cam.eye();
    p.cam_pos[0] = e.x;
    p.cam_pos[1] = e.y;
    p.cam_pos[2] = e.z;
    p.cam_pos[3] = 1.0f;
    if (clip.on) {
        // normal = sign·axis, offset w = sign·offset → discard where dot(N,p) > w cuts the chosen half
        // at coordinate `offset` (see the derivation in mesh_render.hpp / the shader).
        const rime::core::Vec3 n = axis_unit(clip.axis) * clip.sign;
        p.clip_plane[0] = n.x;
        p.clip_plane[1] = n.y;
        p.clip_plane[2] = n.z;
        p.clip_plane[3] = clip.sign * clip.offset;
    } else {
        p.clip_plane[0] = p.clip_plane[1] = p.clip_plane[2] = 0.0f;
        p.clip_plane[3] = 1e30f; // disabled: nothing is clipped
    }
    set_field_push(p, field, field_on);
    return p;
}

bool write_ppm(const std::string& path,
               const std::vector<std::uint8_t>& rgba,
               std::uint32_t w,
               std::uint32_t h) {
    std::ofstream out(path, std::ios::binary);
    if (!out) return false;
    out << "P6\n" << w << ' ' << h << "\n255\n";
    for (std::size_t i = 0; i < static_cast<std::size_t>(w) * h; ++i) {
        out.write(reinterpret_cast<const char*>(&rgba[i * 4]), 3); // RGB, drop alpha
    }
    return static_cast<bool>(out);
}

// Off-screen path: render one frame to `out_path` (PPM) and report how much of the frame the part
// covers. No window/display needed — the render the CI gate asserts on.
int run_offscreen(const CpuMesh& mesh,
                  const std::string& out_path,
                  std::uint32_t size,
                  rime::core::Vec3 world_up,
                  Clip clip,
                  const ScalarField* field,
                  bool field_on) {
    rime::rhi::DeviceDesc desc{};
    desc.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(desc);
    if (!device) {
        std::fprintf(stderr, "icem_viewer: no Vulkan device available (driver / lavapipe / MoltenVK?)\n");
        return 1;
    }

    OrbitCamera cam;
    setup_camera(cam, mesh, 1.0f, world_up); // square image → aspect 1

    // A sectioned snapshot cuts through the part center along the chosen axis.
    if (clip.on) clip.offset = rime::core::dot(mesh.center(), axis_unit(clip.axis));

    const bool use_field = field != nullptr && field_on;
    const float* frgba = use_field ? field->rgba.data() : nullptr;
    const std::uint32_t fnx = use_field ? field->nx : 1;
    const std::uint32_t fny = use_field ? field->ny : 1;
    const std::uint32_t fnz = use_field ? field->nz : 1;

    const std::vector<std::uint8_t> px = rime::viewer::render_mesh_offscreen(*device,
                                                                            size,
                                                                            mesh,
                                                                            make_push(cam, 1.0f, clip, field, field_on),
                                                                            kClear,
                                                                            mesh_vert_spv,
                                                                            sizeof(mesh_vert_spv),
                                                                            mesh_frag_spv,
                                                                            sizeof(mesh_frag_spv),
                                                                            frgba,
                                                                            fnx,
                                                                            fny,
                                                                            fnz);

    std::size_t lit = 0;
    for (std::size_t i = 0; i < static_cast<std::size_t>(size) * size; ++i) {
        // A pixel is "part" if it is brighter than the dark background in any channel.
        if (px[i * 4 + 0] > 40 || px[i * 4 + 1] > 40 || px[i * 4 + 2] > 40) ++lit;
    }
    const double pct = 100.0 * static_cast<double>(lit) / (static_cast<double>(size) * size);
    std::printf("icem_viewer: rendered %u triangles on '%s'%s — part covers %.1f%% of a %ux%u frame\n",
                mesh.triangle_count(),
                device->adapter().name.c_str(),
                use_field ? " (field colormap)" : "",
                pct,
                size,
                size);

    if (!write_ppm(out_path, px, size, size)) {
        std::fprintf(stderr, "icem_viewer: could not write '%s'\n", out_path.c_str());
        return 1;
    }
    std::printf("icem_viewer: wrote %s\n", out_path.c_str());
    return 0;
}

// Create a depth target sized to the swapchain; recreated alongside the swapchain on resize.
rime::rhi::TextureHandle make_depth(rime::rhi::Device& device, rime::rhi::Extent2D extent) {
    rime::rhi::TextureDesc td{};
    td.extent = extent;
    td.format = rime::rhi::Format::D32Float;
    td.usage = rime::rhi::TextureUsage::DepthStencil;
    td.debug_name = "icem-viewer-depth";
    return device.create_texture(td);
}

// Windowed path: present the lit, orbitable part until the window closes (or max_frames is reached).
bool run_windowed(const CpuMesh& mesh,
                  rime::core::Vec3 world_up,
                  int max_frames,
                  const ScalarField* field,
                  bool field_on) {
    using namespace rime::platform;

    if (!init()) return false;
    WindowDesc wd{};
    wd.title = "Rime — ICEM viewer";
    wd.width = 1280;
    wd.height = 720;
    auto window = create_window(wd);
    if (!window) {
        shutdown();
        return false;
    }
    window->show();

    rime::rhi::DeviceDesc dd{};
    dd.app_name = "03-icem-viewer";
    auto device = rime::rhi::create_device(dd);
    if (!device) {
        shutdown();
        return false;
    }

    rime::rhi::SwapchainDesc sd{};
    sd.window = window->native_handle();
    const Extent2D fb = window->framebuffer_size();
    sd.extent = {fb.width, fb.height};
    auto swapchain = device->create_swapchain(sd);
    if (!swapchain) {
        device.reset();
        shutdown();
        return false;
    }

    // Upload the field volume once (if any); toggling G only flips the cheap push-constant flag.
    const float* frgba = field ? field->rgba.data() : nullptr;
    const std::uint32_t fnx = field ? field->nx : 1;
    const std::uint32_t fny = field ? field->ny : 1;
    const std::uint32_t fnz = field ? field->nz : 1;
    auto gpu = rime::viewer::make_mesh(*device,
                                       swapchain->format(),
                                       rime::rhi::Format::D32Float,
                                       mesh,
                                       mesh_vert_spv,
                                       sizeof(mesh_vert_spv),
                                       mesh_frag_spv,
                                       sizeof(mesh_frag_spv),
                                       frgba,
                                       fnx,
                                       fny,
                                       fnz);
    rime::viewer::Legend legend = rime::viewer::make_legend(*device,
                                                            swapchain->format(),
                                                            legend_vert_spv,
                                                            sizeof(legend_vert_spv),
                                                            legend_frag_spv,
                                                            sizeof(legend_frag_spv));
    rime::rhi::TextureHandle depth = make_depth(*device, swapchain->extent());

    OrbitCamera cam;
    {
        const rime::rhi::Extent2D e = swapchain->extent();
        setup_camera(cam, mesh, static_cast<float>(e.width) / static_cast<float>(e.height), world_up);
    }

    Clip clip;
    clip.offset = rime::core::dot(mesh.center(), axis_unit(clip.axis));
    const float clip_step = std::max(std::max(mesh.radius(), 1e-4f) * 0.02f, 1e-5f);
    bool show_field = field != nullptr && field_on;

    std::printf("icem_viewer: presenting %u triangles on '%s'.\n"
                "  camera: drag=orbit, right-drag=pan, wheel=zoom, F=reframe, ESC=quit\n"
                "  section: C=toggle, X/Y/Z=axis, N=flip side, [ ]=move plane\n",
                mesh.triangle_count(),
                device->adapter().name.c_str());
    if (field) {
        std::printf("  field: '%s' [%s] range %.4g .. %.4g — G=toggle colormap (%s)\n",
                    field->name.c_str(),
                    field->unit.c_str(),
                    static_cast<double>(field->vmin),
                    static_cast<double>(field->vmax),
                    show_field ? "on" : "off");
    }

    Input input;
    int frames = 0;
    while (pump_events() && !window->should_close()) {
        if (max_frames > 0 && frames >= max_frames) break;

        input.new_frame();
        Event e{};
        while (poll_event(e)) input.process(e);
        if (input.key_pressed(Key::Escape)) window->request_close();

        const rime::rhi::Extent2D ext = swapchain->extent();
        const float h = static_cast<float>(ext.height);
        const float aspect = static_cast<float>(ext.width) / h;
        if (input.mouse_down(MouseButton::Left)) {
            cam.orbit(input.mouse_dx() * 0.008f, -input.mouse_dy() * 0.008f);
        }
        if (input.mouse_down(MouseButton::Right) || input.mouse_down(MouseButton::Middle)) {
            cam.pan(input.mouse_dx() / h, input.mouse_dy() / h);
        }
        if (input.wheel_y() != 0.0f) cam.zoom(input.wheel_y());
        if (input.key_pressed(Key::F)) cam.frame(mesh.center(), std::max(mesh.radius(), 1e-4f), aspect);

        // Cross-section controls. Selecting an axis re-centers the plane on the part.
        if (input.key_pressed(Key::C)) clip.on = !clip.on;
        if (input.key_pressed(Key::X)) {
            clip.axis = 0;
            clip.offset = rime::core::dot(mesh.center(), axis_unit(0));
        }
        if (input.key_pressed(Key::Y)) {
            clip.axis = 1;
            clip.offset = rime::core::dot(mesh.center(), axis_unit(1));
        }
        if (input.key_pressed(Key::Z)) {
            clip.axis = 2;
            clip.offset = rime::core::dot(mesh.center(), axis_unit(2));
        }
        if (input.key_pressed(Key::N)) clip.sign = -clip.sign;
        if (input.key_down(Key::LeftBracket)) clip.offset -= clip_step;
        if (input.key_down(Key::RightBracket)) clip.offset += clip_step;
        // Field colormap toggle (only meaningful when a field was loaded).
        if (input.key_pressed(Key::G) && field) show_field = !show_field;

        rime::rhi::TextureHandle target = swapchain->acquire_next_image();
        if (!target.is_valid()) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
            continue;
        }

        auto cmd = device->begin_commands();
        rime::viewer::record_mesh(
            *cmd, gpu, target, depth, ext, make_push(cam, aspect, clip, field, show_field), kClear);
        if (field && show_field) rime::viewer::record_legend(*cmd, legend, target, ext);
        if (!swapchain->present(*cmd)) {
            device->wait_idle();
            const Extent2D s = window->framebuffer_size();
            swapchain->recreate({s.width, s.height});
            device->destroy(depth);
            depth = make_depth(*device, swapchain->extent());
        }
        ++frames;
    }

    device->wait_idle();
    device->destroy(depth);
    rime::viewer::destroy_legend(*device, legend);
    rime::viewer::destroy_mesh(*device, gpu);
    swapchain.reset();
    device.reset();
    shutdown();
    std::printf("icem_viewer: presented %d frame%s.\n", frames, frames == 1 ? "" : "s");
    return true;
}

// Derive the sibling field file for an STL path: replace the extension with .icef (so ICEM's
// `field.stl` pairs with its `field.icef`). Returns empty for an empty path.
std::string sibling_icef(const std::string& stl_path) {
    if (stl_path.empty()) return {};
    const std::size_t slash = stl_path.find_last_of("/\\");
    const std::size_t dot = stl_path.find_last_of('.');
    if (dot != std::string::npos && (slash == std::string::npos || dot > slash)) {
        return stl_path.substr(0, dot) + ".icef";
    }
    return stl_path + ".icef";
}

} // namespace

int main(int argc, char** argv) {
    std::string stl_path;
    std::string field_path; // explicit --field; else a sibling <stem>.icef is tried
    std::string out_path = "icem_view.ppm";
    bool offscreen = false;
    bool no_field = false;
    std::uint32_t size = 512;
    int frames = 0;
    rime::core::Vec3 world_up{0.0f, 0.0f, 1.0f}; // ICEM parts are authored z-up
    Clip clip; // off unless --clip is given (offscreen); the window toggles it interactively

    for (int i = 1; i < argc; ++i) {
        const std::string_view a(argv[i]);
        if (a == "--offscreen" || a == "--headless") {
            offscreen = true;
            if (i + 1 < argc && argv[i + 1][0] != '-') out_path = argv[++i];
        } else if (a == "--windowed") {
            offscreen = false;
        } else if (a == "--field" && i + 1 < argc) {
            field_path = argv[++i];
        } else if (a == "--no-field") {
            no_field = true;
        } else if (a == "--clip" && i + 1 < argc) {
            const std::string_view ax(argv[++i]);
            clip.on = true;
            clip.axis = (ax == "y") ? 1 : (ax == "z") ? 2 : 0;
        } else if (a == "--size" && i + 1 < argc) {
            size = static_cast<std::uint32_t>(std::max(8, std::atoi(argv[++i])));
        } else if (a == "--frames" && i + 1 < argc) {
            frames = std::atoi(argv[++i]);
        } else if (a == "--up-y") {
            world_up = {0.0f, 1.0f, 0.0f};
        } else if (!a.empty() && a[0] != '-') {
            stl_path = a;
        }
    }

    CpuMesh mesh;
    if (!stl_path.empty()) {
        auto loaded = rime::viewer::load_stl_binary_file(stl_path);
        if (!loaded) {
            std::fprintf(stderr, "icem_viewer: could not load binary STL '%s'\n", stl_path.c_str());
            return 1;
        }
        mesh = std::move(*loaded);
    } else {
        std::printf("icem_viewer: no STL given — showing a unit cube. Pass a binary STL to view a part.\n");
        mesh = rime::viewer::make_unit_cube();
    }

    // Load a simulation field: an explicit --field path, else the STL's sibling <stem>.icef if present.
    std::optional<ScalarField> field;
    const bool explicit_field = !field_path.empty();
    if (field_path.empty()) field_path = sibling_icef(stl_path);
    if (!field_path.empty()) {
        field = rime::viewer::load_icef_scalar(field_path);
        if (field) {
            std::printf("icem_viewer: loaded field '%s' [%s] range %.4g .. %.4g on a %ux%ux%u grid (%s)\n",
                        field->name.c_str(),
                        field->unit.c_str(),
                        static_cast<double>(field->vmin),
                        static_cast<double>(field->vmax),
                        field->nx,
                        field->ny,
                        field->nz,
                        field_path.c_str());
        } else if (explicit_field) {
            std::fprintf(stderr, "icem_viewer: could not load field '%s'\n", field_path.c_str());
        }
    }

    const ScalarField* fptr = field ? &*field : nullptr;
    const bool field_on = field.has_value() && !no_field;

    if (offscreen) return run_offscreen(mesh, out_path, size, world_up, clip, fptr, field_on);
    if (run_windowed(mesh, world_up, frames, fptr, field_on)) return 0;
    std::printf("icem_viewer: no window/display — falling back to off-screen (%s).\n", out_path.c_str());
    return run_offscreen(mesh, out_path, size, world_up, clip, fptr, field_on);
}
